import Foundation

let rulesListES = [
"1. Invierte en un buen colchón: dormir es muy importante para tu salud y bienestar.",
    "2. Es una buena idea tener un juego básico de herramientas en tu coche: incluso si no puedes arreglar tu coche tú mismo, alguien puede ayudarte.",
    "3. Prepara una lista de cosas que necesitas llevar contigo antes de cada viaje.",
    "4. Siempre lleva un botiquín de primeros auxilios contigo.",
    "5. Planea tus viajes con antelación y presta atención a las condiciones climáticas.",
    "6. Aprende a usar diferentes fuentes de energía, desde paneles solares hasta un generador.",
    "7. Siempre lleva suficiente agua potable contigo.",
    "8. Prueba todo el equipo de tu camper o remolque antes de tu primer viaje.",
    "9. Aprende cómo funciona el sistema de drenaje y cómo mantener la higiene.",
    "10. Siempre cierra las puertas y ventanas cuando salgas del camper o remolque.",
    "11. Recuerda realizar el mantenimiento y las inspecciones de tu camper o remolque con regularidad.",
    "12. Abastécete de medicamentos necesarios, como analgésicos y carbón activado.",
    "13. Revisa el estado técnico de tu vehículo antes de salir.",
    "14. Si te diriges al campo, incluso cuando sea verano en el suelo, conduce con neumáticos de invierno.",
    "15. Siempre lleva una botella de aceite de motor específica para tu vehículo en tu coche.",
    "16. Un camino difícil de acceso suele ocultar un gran lugar salvaje al final.",
    "17. Sé considerado y piensa en los demás. Si estacionas entre otros campers, mantén una distancia adecuada.",
    "18. Si sales a caminar al atardecer, lleva una linterna o un powerbank con un cable para tu teléfono.",
    "19. Si te confundes en el camino, no des la vuelta, déjate llevar por la aventura, pero con precaución.",
    "20. Si subes una colina en segunda marcha, también deberías bajarla en segunda marcha.",
    "21. Si viajas solo, comparte tu ubicación frecuentemente con tus familiares cercanos.",
    "22. Si tienes la oportunidad de rellenar agua o vaciar las aguas grises y negras, hazlo. Puede que el centro de servicio más cercano no esté en tu ruta.",
    "23. Si viajas con otra persona, establece siempre una forma de comunicación en caso de que se pierdan o separen.",
    "24. Lleva tu basura contigo si no hay un contenedor de basura cercano.",
    "25. Una manguera larga para llenar agua siempre es mejor que una corta.",
    "26. Es una buena idea tener una variedad de adaptadores para válvulas de agua; nunca sabes qué encontrarás en el sitio.",
    "27. ¿El camino al lugar para dormir era cuesta abajo? Revisa el clima, si se espera lluvia cambia a otro lugar, por la mañana podrías tener problemas para salir.",
    "28. Nunca te detengas si alguien te hace señas en una carretera normal o en la autopista.",
    "29. Ahorra dinero, agua, gas y electricidad.",
    "30. El minimalismo es tu amigo. Al empacar para un viaje largo, no lleves cosas innecesarias. Con el tiempo notarás que no las extrañas en absoluto.",
    "31. Planificación. Si has encontrado un lugar genial en Google Maps o Park4Night, verifica si hay otros lugares interesantes cerca. Puede que el lugar ya no esté disponible para pernoctar.",
    "32. Seguridad. Si llegas a un lugar y no te sientes seguro, cámbialo por otro.",
    "33. En grupo es mejor. Si no te sientes seguro en la zona en la que te encuentras, busca otros campers, será más seguro estar con más campers.",
    "34. Tesoros. Encuentra un lugar en tu coche para tus objetos de valor. Puedes instalar una pequeña caja fuerte o una caja metálica con cerradura. Recuerda asegurarlo adecuadamente contra robos.",
    "35. Respeta el medio ambiente: Cuida el entorno en el que viajas. Sigue las normas ambientales, como dejar el lugar limpio y separar la basura.",
    "36. Disfruta de tu libertad: Goza de la libertad y la aventura que ofrece la vida en camper. Haz de tu viaje una experiencia inolvidable. ¡Vive este momento!",
    "37. Cultura y tradición. Recuerda respetar las culturas y tradiciones locales.",
    "38. Respeta las leyes de tránsito del país por el que viajas. Evita multas.",
    "39. Limita tu uso de artículos desechables de plástico.",
    "40. En viajes largos, haz paradas cortas para estirarte. También puedes cambiar la posición de tu asiento; esto aliviará tu columna vertebral.",
    "41. Sé flexible y abierto a cambios en los planes, ya que siempre puede surgir algo inesperado al viajar.",
    "42. Prepárate para la falta de cobertura de teléfono o internet en algunos lugares.",
    "43. Recuerda descansar y relajarte, no solo viajar sin parar.",
    "44. Antes de viajar a un país, descarga mapas offline no solo del país de destino sino también de los que atravesarás.",
    "45. Instala aplicaciones adecuadas para encontrar lugares donde dormir (Google Maps, Park4Night, etc.).",
    "46. Lleva siempre suficiente efectivo o una tarjeta de débito para pagar los gastos de viaje.",
    "47. Divide grandes cantidades de efectivo en varias más pequeñas y escóndelas en lugares discretos. La guantera del coche es lo primero que revisará un posible ladrón.",
    "48. Da un buen ejemplo. Si ves basura dejada por otros, intenta recogerla y desecharla en un lugar adecuado.",
    "49. Contrata un seguro de viaje, asistencia, remolque.",
    "50. Cuida tu seguridad y la de tus seres queridos. Siempre usa el cinturón de seguridad y evita conducir después de beber alcohol.",
    "51. Lleva una copia física de los documentos importantes como el pasaporte, licencia de conducir y seguro de viaje.",
        "52. Si viajas en invierno, lleva cadenas para la nieve y verifica que tu vehículo esté preparado para temperaturas bajas.",
        "53. Aprende algunas palabras básicas en el idioma del lugar al que viajas. Podría ser útil en caso de emergencia.",
        "54. Nunca dejes objetos de valor a la vista dentro de tu vehículo.",
        "55. Lleva contigo un cargador solar para tus dispositivos en caso de que te quedes sin batería.",
        "56. Si viajas con niños, asegúrate de que tengan entretenimiento adecuado para viajes largos.",
        "57. Mantén una rutina de limpieza dentro de tu camper para evitar el desorden.",
        "58. Lleva un mapa físico además de las aplicaciones en línea, ya que en algunas áreas podrías quedarte sin conexión.",
        "59. Aprende cómo realizar reparaciones básicas en tu vehículo.",
        "60. Respeta las áreas privadas y estaciona solo en lugares permitidos.",
        "61. Lleva una linterna potente y pilas de repuesto.",
        "62. Siempre verifica los horarios y regulaciones locales antes de estacionarte o acampar.",
        "63. Lleva ropa adecuada para cambios bruscos de clima.",
        "64. Si viajas con mascotas, asegúrate de llevar su comida, agua y accesorios necesarios.",
        "65. Aprende técnicas básicas de primeros auxilios.",
        "66. Nunca confíes completamente en los sistemas GPS, siempre verifica las rutas por tu cuenta.",
        "67. Sé respetuoso con la fauna local y evita alimentarla o interactuar en exceso.",
        "68. Asegúrate de llevar una buena silla plegable para relajarte al aire libre.",
        "69. Investiga sobre los lugares de interés cercanos para enriquecer tu experiencia de viaje.",
        "70. Comparte tus experiencias de viaje con otros viajeros; podrías aprender consejos útiles.",
        "71. Mantén una actitud positiva y flexible ante contratiempos.",
        "72. Lleva contigo un diario de viaje para registrar tus aventuras.",
        "73. Si encuentras un lugar espectacular, tómate el tiempo para disfrutarlo plenamente en lugar de apresurarte a seguir.",
        "74. Mantén la calma si enfrentas problemas mecánicos y busca ayuda profesional si es necesario.",
        "75. Aprovecha las redes sociales para conectar con otros viajeros y compartir recomendaciones.",
        "76. Antes de partir, revisa los frenos, luces y niveles de fluidos de tu vehículo.",
        "77. Lleva contigo repelente de insectos si planeas estar en áreas al aire libre por mucho tiempo.",
        "78. Familiarízate con las reglas de tráfico locales y respétalas siempre.",
        "79. Planifica paradas regulares para descansar y evitar la fatiga del conductor.",
    "80. Sé amable con los locales. Es probable que necesites su ayuda si tienes un problema inesperado.",
        "81. Un dron es un gran dispositivo para crear recuerdos de viaje. Recuerda respetar la seguridad y la privacidad de otras personas.",
        "82. Si tienes un dron, verifica las regulaciones actuales en el país en el que te encuentras. Respeta las prohibiciones de vuelo en áreas designadas.",
        "83. Si tienes un dron, nunca despegues cerca de un aeropuerto.",
        "84. No obstruyas la vista desde la casa, restaurante o terraza de alguien.",
        "85. Si tu furgoneta/autocaravana ocupa más de un espacio de estacionamiento, estaciona en otro lugar.",
        "86. Lee/traduce la información en los letreros.",
        "87. A veces encontrar un lugar de estacionamiento puede ser un problema. Puedes preguntar a los locales o a la policía por un lugar conveniente para quedarte.",
        "88. Comienza a escribir un diario de viaje, puede ser un gran recuerdo.",
        "89. Lleva un juego de mesa o cartas contigo, añadirá variedad a tu tiempo durante el mal tiempo.",
        "90. Aborda cada día estratégicamente. Planifica las compras, el mantenimiento, el vaciado del inodoro y el agua gris el día anterior.",
        "91. Cocinar en una caravana/autocaravana lleva mucho más tiempo que en una sartén rápida.",
        "92. Prepárate para limpiar el coche con frecuencia. Abastécete de una escoba o aspiradora.",
        "93. Prepárate para numerosos insectos, no solo mosquitos. Una mosquitera puede ser solo una solución parcial.",
        "94. No enciendas una luz por la noche con la puerta entreabierta.",
        "95. Antes de salir, verifica el estado de tu rueda de repuesto, también puedes obtener un kit de reparación de neumáticos. Esto te permitirá llegar al vulcanizador más cercano.",
        "96. Prepárate para salir de tu zona de confort.",
        "97. Si trabajas de forma remota, asegúrate de tener un lugar cómodo para trabajar. Una tumbona y una playa se ven bien solo en las fotos.",
        "98. Cada día es una aventura. Trátalo como un buen momento.",
        "99. Si viajas con una mascota, mantenla cerca de tu coche.",
        "100. Cuando no haya cobertura en tu teléfono, es una buena idea tener un mapa de papel contigo.",
        "101. Las condiciones climáticas durante una caminata pueden cambiar repentinamente, es aconsejable llevar un impermeable que pueda caber en tu bolsillo.",
        "102. Antes de viajar, verifica la vigencia de tu pasaporte y otros documentos.",
        "103. Obtén una Tarjeta Sanitaria Europea (EHIC).",
        "104. Lleva un hervidor pequeño para hervir agua para café y ahorrar tiempo y agua.",
        "105. Recuerda el protector solar UV, en verano, invierno e incluso cuando vayas a las montañas.",
        "106. Haz una lista de compras para evitar gastos innecesarios/adicionales.",
        "107. No empaques en el último minuto, prepara los artículos necesarios al menos dos días antes.",
        "108. Una botella de alcohol u otro regalo es una buena idea como agradecimiento por la ayuda." ]
