//  Created by Mateusz Mlynarski
// All rights reserved

import Foundation

let rulesListPL: [String] = [
    "1. Zainwestuj w dobry materac - sen jest bardzo ważny dla Twojego zdrowia i samopoczucia.",
    "2. Warto mieć w aucie podstawową walizkę z narzędziami, nawet jeśli sam nie potrafisz naprawić swojego samochodu, ktoś może Ci pomóc.",
    "3. Przygotuj listę rzeczy, które musisz zabrać ze sobą przed każdym wyjazdem.",
    "4. Zawsze miej ze sobą zestaw pierwszej pomocy.",
    "5. Planuj swoje wyjazdy z wyprzedzeniem i zwracaj uwagę na warunki atmosferyczne.",
    "6. Naucz się, jak korzystać z różnych źródeł energii - od paneli słonecznych, po generator.",
    "7. Zawsze miej ze sobą wystarczającą ilość wody pitnej.",
    "8. Przetestuj wszystkie urządzenia w kamperze lub przyczepie przed wyjazdem.",
    "9. Naucz się jak działa system odprowadzania ściekóww w twoim kamperze lub przyczepie.",
    "10. Zawsze zamykaj drzwi i okna, kiedy opuszczasz kampera lub przyczepę.",
    "11. Pamiętaj o regularnym serwisowaniu i przeglądach kampera lub przyczepy.",
    "12. Zaopatrz się w niezbędne leki takie jak środki przeciwbólowe czy węgiel aktywny.",
    "13. Przed wyjazdem sprawdź stan techniczny swojego pojazdu.",
    "14. Jeśli wyjeżdżasz w ziemie, nawet gdy na miejscu jest lato, jedź na zimowych oponach.",
    "15. Zawsze miej w samochodzie butelkę oleju silnikowego dedykowanego do twojego pojazdu.",
    "16. Trudna droga dojazdowa zazwyczaj kryje na końcu wspaniała dziką miejscówkę.",
    "17. Dbaj i myśl o innych, jeśli parkujesz miedzy innymi kamperami, zachowaj odpowiedni odstęp.",
    "18. Jeśli wychodzisz późnym popołudniem na spacer, zabieraj ze sobą latarkę lub powerbenka z kablem do telefonu.",
    "19. Jeśli pomylisz drogę, nie zawracaj, daj się ponieść przygodzie, ale oczywiście z rozwagą.",
    "20. Jeśli wjeżdżasz pod górę na drugim biegu, powianeś zjeżdżać z góry również na drugim biegu.",
    "21. Jeśli podróżujesz sam, udostępniaj często swoją lokalizację najbliższej rodzinie.",
    "22. Jeśli masz możliwość uzupełnić wodę, wylać szarą, czarną wodę, zrób to. Może się okazać że najbliższy serwis będzie nie po drodze.",
    "23. Jeśli podróżujesz z drugą osobą, zawsze ustalcie między sobą sposób komunikacji na wypadek zgubienia się czy rozdzielenia.",
    "24. Jeśli w pobliżu nie ma kosza, śmieci zabieraj ze sobą.",
    "25. Długi wąż do zatankowania wody jest zawsze lepszy niż krótki.",
    "26. Warto zaopatrzyć się w różne końcówki nakręcane na zawory z woda, nigdy nie wiesz co zastaniesz na miejscu.",
    "27. Droga na miejsce do spania była z górki? Sprawdź pogodę, jeśli ma padać zmień miejsce na inne, rano możesz mieć problem z wyjazdem.",
    "28. Nigdy nie zatrzymuj się gdy ktoś do ciebie macha czy to na zwykłej drodze czy autostradzie.",
    "29. Oszczędzaj wodę, gaz i prąd.",
    "30. Pakując się na długi wyjazd nie zabieraj ze sobą niepotrzebnych rzeczy. Z czasem zauważysz że w ogóle Ci ich nie brakuje.",
    "31. Jeśli znalazłeś super miejscówkę na google maps lub park4night sprawdź czy obok niej są inne ciekawe miejsca. Może się okazać że to miejsce nie będzie już dostępne",
    "32. Jeśli dotarłxś na miejsce i nie czujesz się tam bezpiecznie, zmień miejsce na inne.",
    "33. Jeśli nie czujesz się bezpiecznie w okolicy w której akurat jesteś, rozglądaj się za innymi kamperami, w grupie będzie bezpieczniej",
    "34. Znajdź w swoim aucie miejsce na cenne rzeczy, możesz zainstalować mały sejf lub metalową zamykaną skrzynkę. Pamiętaj by odpowiednio ją zabezpieczyć przed kradzieżą.",
    "35. Dbaj o środowisko, w którym podróżujesz. Przestrzegaj zasad ekologicznych, takich jak pozostawianie miejsca czystym i segreguj śmieci.",
    "36. Ciesz się wolnością i przygodą, którą oferuje van life. Niech podróż stanie się dla Ciebie niesamowitą przygodą i doświadczeniem, które na zawsze pozostaną w Twojej pamięci. Żyj tą chwilą!",
    "37. Pamiętaj o poszanowaniu lokalnych kultur i tradycji.",
    "38. Przestrzegaj przepisów drogowych w kraju, przez który podróżujesz. Unikniesz mandatu.",
    "39. Ogranicz korzystanie z plastikowych jednorazowych przedmiotów, takich jak kubki czy sztućce.",
    "40. Przy długiej podróży rób krótkie przystanki na rozprostowanie, możesz również zmieniać pozycję fotela, to da ulgę twojemu kręgosłupowi.",
    "41. Bądź elastyczny i otwarty na zmiany planów, ponieważ w podróży zawsze może pojawić się coś nieprzewidywalnego.",
    "42. Przygotuj się na brak zasięgu telefonu lub internetu w niektórych miejscach.",
    "43. Pamiętaj, aby wypocząć i zrelaksować się, a nie tylko podróżować non-stop.",
    "44. Przed podróżą do danego kraju, pobierz mapy offline nie tylko kraju docelowego ale też te przez które będziesz przejeżdżać.",
    "45. Zainstaluj odpowiednie aplikacje do znalezienia miejsc do spania (GoogleMaps, Park4Night itp)",
    "46. Zawsze miej przy sobie wystarczającą ilość gotówki lub karty płatnicze, aby móc zapłacić za wydatki podróżne.",
    "47. Wiekszą sumę gotówki podziel na kilka mniejszych i schowaj w nieoczyswitych miejscach. Schowek samochodowy to pierwsza rzecz którą sprawdzi potencjalny złodziej.",
    "48. Daj dobry przykład. Jeśli widzisz śmieci pozostawione przez innych, zbierz je i wyrzucić w odpowiednim miejscu.",
    "49. Kup ubezpieczenie podróżne, assistance, holowanie.",
    "50. Dbaj o bezpieczeństwo swoje i swoich bliskich.",
    "51. Korzystaj z możliwości spotkania nowych ludzi i doświadczania różnych kultur.",
    "52. Bądź gotowy na nieprzewidziane wydatki, takie jak naprawa samochodu lub zakup dodatkowego paliwa.",
    "53. W przypadku braku pomysłu na miejsce do zatrzymania na noc, możesz zapytać o możliwość postoju np na stacji benzynowej.",
    "54. Przygotuj się na różne warunki drogowe, takie jak kamieniste drogi, wysokie góry czy drogi z ostrymi zakrętami.",
    "55. Przestrzegaj zasad dotyczących wjazdu do parków narodowych lub innych obszarów chronionych, aby nie narażać przyrody na szkody, a siebie na dodatkowe wydatki.",
    "56. Bądź cierpliwy, gdy jadąc samochodem napotkasz trudne drogi, natłok ludzi lub problemy z samochodem, które mogą spowodować opóźnienia w podróży.",
    "57. Pamiątki. Pamiętaj by zostawić trochę miejsca na rzeczy zakupione w podróży.",
    "58. Odkrywaj nie tylko nowe miejsca, spróbuj także lokalnej kuchni. Otwórz się na nowe smaki, być może z podróży wrócisz z nowym ulubionym daniem.",
    "59. Przestrzegaj zasad dotyczących kempingu, takich jak pozostawianie miejsca w stanie, w jakim je zastaliśmy oraz przestrzeganie zasad dotyczących ognisk i grillowania.",
    "60. Unikaj zanieczyszczenia środowiska, spróbuj stosować ekologiczne kosmetyki i płyny.",
    "61. Możesz zminimalizować zużycie wody, korzystając z publicznych źródeł, w tym toalet i pryszniców.",
    "62. Spróbuj nauczyć się nowych umiejętności, takich jak gotowanie na ognisku, wspinaczka czy surfowanie, aby poszerzyć swoje horyzonty i czerpać więcej radości z podróży.",
    "63. Małe miasteczka lub wioski w okolicy w której obecnie przebywasz mogą być dla ciebie lepszą atrakcją niż zatłoczone turystyczne miasto.",
    "64. Warto zawsze mieć w aucie podstawowe produkty spożywcze takie jak mąka, drożdże, cukier, sól.",
    "65. Ucz się na błędach i nie przestawaj eksperymentować z różnymi rozwiązaniami.",
    "66. Pamiętaj o wykorzystywaniu czasu wolnego do rozwoju swoich zainteresowań i pasji, czy to poprzez czytanie, naukę języków obcych czy tworzenie sztuki.",
    "67. Ciesz się naturą i pozwól sobie na chwile refleksji i medytacji, aby zyskać nowe perspektywy na swoje życie i cele.",
    "68. Bądź gotowy na niespodziewane wyzwania i sytuacje, a także na to, że nie zawsze będzie łatwo.",
    "69. Jeśli podróżujesz sam/sama, pozostań trzeźwy, nie wiesz czy nie przyjedzie Policja i nakaże przeparkowania samochodu.",
    "70. Nie wchodź w dyskusję z lokalną policją i mieszkańcami. Uszanuj ich.",
    "71. Bądź wdzięczny za każdą chwilę i każde doświadczenie, które spotkają Cię na Twojej drodze, a także za każdą osobę, która pojawi się w Twoim życiu i podzieli się z Tobą swoimi historiami i mądrościami.",
    "72. Pamiętaj, że podróżowanie samochodem wiąże się z pewnym ryzykiem, więc zawsze bądź czujny i ostrożny na drodze.",
    "73. Dbaj o swoje relacje z rodziną i przyjaciółmi, utrzymując z nimi kontakt i dzieląc się swoimi doświadczeniami.",
    "74. Bądź otwarty na naukę i rozwój osobisty, wykorzystując czas spędzony w samochodzie na słuchanie audiobooków, podcastów czy ucząc się nowych umiejętności.",
    "75. Uważaj na kieszonkowców w komunikacji miejskiej. Miej zawsze oko na swój bagaż.",
    "76. Jeśli podróżujesz ze zwierzakiem zadbaj o to by miał odpowiednią temperaturę i dostęp do wody pitnej.",
    "77. Zamień chemiczne środki do toalety, ekologicznymi np saszetki lub tabletki do szamb.",
    "78. Nie zostawiaj na noc sprzętu turystycznego (Krzesełek, stolika, grilla) na zewnątrz.",
    "79. Bądź pokorny/a wobec miejscowych i wszystkich przechodniów. Uśmiechnij się! Jesteś częścią ich codziennej rutyny, ich miejsca i domowych terenów.",
    "80. Bądź życzliwy dla miejscowych. Istnieje prawdopodobieństwo, że będziesz potrzebował/a ich pomocy, jeśli będziesz miał/a niespodziewany problem.",
    "81. Dron to wspaniałe urządzenie do tworzenia pamiątek z podróży. Pamiętaj by zachować bezpieczeństwo i prywatność innych ludzi.",
    "82. Jeśli masz drona, sprawdź obowiązujące przepisy w kraju w którym jesteś. Przestrzegaj zakazów lotu w wydzielonych strefach.",
    "83. Jeśli masz drona, nigdy nie startuj blisko lotniska.",
    "84. Nie zasłaniaj swoim autem, widoku z czyjegoś domu, restauracji czy tarasu.",
    "85. Jeśli Twój van / samochód kempingowy zajmuje więcej niż jedno miejsce parkingowe, zaparkujcie w innym miejscu.",
    "86. Czytaj lub tłumacz informacje na znakach.",
    "87. Czasami znalezienie miejsca parkingowego może być problemem. Możesz zapytać miejscowych lub policję o wskazanie dogodnego miejsca na nocleg.",
    "88. Zacznij pisać dziennik z podróży, może to być świetna pamiątka.",
    "89. Zabierz ze sobą grę planszową lub karty, urozmaici to czas podczas złej pogody.",
    "90. Zaplanuj zakupy, taknowanie wody, opróżnienie toalety i szarej wody dzień wcześniej.",
    "91. Weź pod uwagę, że gotowanie w kamperze/campervanie zajmuje znacznie więcej czasu niż w mieszkaniu.",
    "92. Przygotuj się na częste sprzątanie auta. Zaopatrz się w zmiotkę lub odkurzacz.",
    "93. Przygotuj się na liczne owady, nie tylko komary. Moskitiera może być tylko częściowym rozwiązaniem.",
    "94. Nie zapalaj wieczorem światła przy uchylonych drzwiach.",
    "95. Przed wyjazdem sprawdź w jakim stanie jest twoje koło zapasowe, możesz również zaopatrzyć się w zestaw do naprawy opony. Pozwoli to dojechać do najbliższej wulkanizacji.",
    "96. Bądź gotowy wyjść ze swojej strefy komfortu.",
    "97. Jeśli pracujesz zdalnie, zadbaj o wygodne miejsce do pracy. Leżak i plaża fajnie wygląda tylko na zdjęciach.",
    "98. Każdy dzień to przygoda. Traktuj to jako dobrą zabawę.",
    "99. Jeśli podróżujesz ze zwierzakiem, trzymaj go blisko swojego auta.",
    "100. Gdy braknie zasięgu w telefonie, warto mieć ze sobą papierową mapę.",
    "101. Warunki pogodowe podczas spaceru mogą się nagle zmienić.Wsrto mieć ze sobą płaszcz przeciwdeszczowy,który zmieścisz w kieszeni.",
    "102. Przed podróżą sprawdż ważność paszportu i innych dokumentów.",
    "103. Wyrób Europejska Karta Ubezpieczenia Zdrowotnego (EKUZ).",
    "104. Zaopatrz się w mały czajnik do zagotowania wody na kawę zaoszczędzisz czas i wodę.",
    "105. Pamiętaj o kremie z filtrem UV, latem, zimą a nawet jak idziesz w góry.",
    "106. Rób listę zakupoów. Unikniesz niepotrzebnych/dodatkowych wydatków.",
    "107. Nie pakuj się na ostatnią chwile, naszykuj potrzebne rzeczy, przynajmniej dwa dni wcześniej.",
    "108. Butelka alkoholu lub inny prezent to dobry pomysł by wręczyć w podzięce za pomoc.",
    "109. Jeśli jesteś blisko stacji paliw i świeci się rezerwa, zatankuj, bo kolejna stacja może być za daleko.",
    "110. Dziel się swoimi doświadczeniami z innymi.",
    "111. Gdy jest okazja na zatankowanie wody lub opróżnienie toalety, zrób to, podobnie jak w przypadku paliwa, nigdy nie wiesz kiedy będzie kolejna szansa.",
    "112. Jeśli podróżujesz z kimś, szczególnie w krajach po za UE, warto ustalic sposób komunikacji w sytuacji braku internetu.",
    "113. Jeśli masz złe przeczucia odnośnie stanu swojego pojazdu nie ignoruj go.",
    "114. Przy naprawie samochodu zaczynaj od najdroższych rzeczy, jeśli planujesz naprawy w tańszym kraju pamiętaj może Cię to kosztować dwa razy więcej.",
    "115. Kiedy masz złe przeczucia co do miejsca w którym zamierzasz nocować, znajdz inne, po co kusić los.",
    "116. Nie odkładaj sniadania na później, w ciągu dnia wiele się dzieje a pierwszy posiłek o 19 nazywany zwykle jest kolacja.",
    "117. Jeśli czas nie pokrywa się z kilometrami rozważ zmianę miejscowki, może to oznaczać drogę bardzo słabej jakości lub offroad.",
    "118. Jeśli mapy Google źle wskazują drogę, warto sprawdzić ją w innej aplikacji.",
    "119. Jeśli coś się zepsuło i nagle się samo naprawiło to znaczy że nadal jest zepsute",
    "120. Teytytki szara taśma i WD 40 miej zawsze w pogotowiu",
    "121. Gdy wczorajszego wieczoru impreza się przedłużyła, odczekaj zanim wsiądziesz za kierownice lub udaj się na komisariat Policji i poproś o badanie alkomatem.",
    "122. Jeśli jesteś w górach i spadł śnieg, poczekaj aż pojawi się pług śniezny. Jedź za nim, to znacznie ułatwi drogę.",
    "123. Jeżeli gdzieś wyjeżdzasz, zawsze bierz ze sobą paszport, nigdy nie wiesz gdzie cię poniesie przygoda.",
    "124. Zapoznaj się z zasadami ruchu drogowego i kulturą jazdy tamtejszych kierowców",
    "125. Sprawdź jakie jesy obowiązkowe wyposażenie samochodu w kraju do którego jedziesz, a także przez jakie przejeżdżasz. (kamizelki, gaśnica, trójkąt)",
    "126. Pamiętaj o zabraniu zielonej karty gdy wyjedzasz autem za granice.",
    "127. Jeśli to możliwe wykup dodatkowe ubezpieczenie obowiązujące w kraju do którego jedziesz.",
    "128. Jeśli planujesz wyjazd po za Unię Europejską sprawdź wymagania w danym kraju.",
    "129. Sprawdź czy w kraju do którego wyjezdzasz są obowiązkowe szczepienia.",
    "130. Zapytaj lokalnych mieszkanscow o atrakcje w okolicy",
    "131. zapoznaj sie z kultura w danym kraju np gesty.",
    "132. Zawsze zapinj pasy bezpieczeństwa, mogą uroatować Ci zycie.",
    "133. Unikaj jazdy po alkoholu, nawet po jednym piwie."
]
