//  Created by Mateusz Mlynarski
// All rights reserved 

import Foundation

let rulesList = [
    "1. Invest in a good mattress - sleep is very important for your health and well-being.",
    "2. It's a good idea to have a basic tool case in your car - even if you can't fix your car yourself, someone can help you.",
    "3. Prepare a list of things you need to take with you before every trip.",
    "4. always have a first aid kit with you.",
    "5. Plan your trips in advance and pay attention to weather conditions.",
    "6. Learn how to use different energy sources - from solar panels to a generator.",
    "7. Always have enough drinking water with you.",
    "8. Test all equipment in your camper or trailer before your first trip.",
    "9. Learn how the drainage system works and how to take care of hygiene.",
    "10. Always lock the doors and windows when you leave the camper or trailer.",
    "11. Remember to regularly service and inspect your camper or trailer.",
    "12. Stock up on necessary medications such as painkillers and activated charcoal.",
    "13. check the technical condition of your vehicle before you leave.",
    "14. If you're heading out into the countryside, even when it's summer on the ground, drive on winter tires.",
    "15. Always have a bottle of motor oil dedicated to your vehicle in your car.",
    "16. A difficult access road usually hides a great wild spot at the end.",
    "17. Take care and think of others, if you park between other campers, keep .adequate distance.",
    "18. if you're going out for a walk in the late afternoon, take a flashlight or powerbench with a cable for your phone. ",
    "19. If you get confused on the road, don't turn back, let yourself be adventurous, but of course with caution.",
    "20. if you go uphill in 2nd gear, you should also go downhill in 2nd gear",
    "21. if you are traveling alone, share your location frequently with your immediate family",
    "22. if you have the opportunity to refill water, pour out gray, black water, do it. You may find that the nearest nearest service center is not on the way.",
    "23. If you are traveling with another person, always establish a way of communication between you in case you get lost or separated.",
    "24. Take your garbage with you if there is no trash can nearby.",
    "25.A long hose for refueling water is always better than a short one.",
    "26. It's a good idea to get a variety of screw-on tips for water valves, you never know what you'll find on site.",
    "27. The road to the sleeping place was downhill? Check the weather, if it's supposed to rain change to another place, in the morning you may have trouble leaving.",
    "28. Never stop when someone waves at you whether on a regular road or highway.",
    "29. Save money, water, gas and electricity.",
    "30. Minimalism is your friend. When packing for a long trip, don't take unnecessary things with you. In time you will notice that you don't lack them at all.",
    "31. Planning. If you have found a super spot on google maps or park4night check to see if there are other interesting places next to it. You may find that the place is no longer available for overnight stays.",
    "32. Safety. If you have arrived at a place and do not feel safe there, change to another place.",
    "33. in a pile is better. If you don't feel safe in the area you happen to be in, look around for other campers, it will be safer to stand somewhere with more campers.",
    "34. Treasures. Find a place in your car for your valuables, you can install a small safe or a metal lockable box. Remember to properly secure it against theft.",
    "35. Respect the environment: Take care of the environment in which you travel. Follow environmental rules, such as leaving the place clean and segregating trash.",
    "36. Enjoy your freedom: Enjoy the freedom and adventure that van life offers. Make your trip an amazing adventure and an experience that you will always remember. Live this moment!",
    "37. Culture and tradition. Remember to respect local cultures and traditions.",
    "38. Observe the traffic laws of the country you are traveling through. Avoid fines.",
    "39. Limit your use of plastic disposable items.",
    "40. When traveling for a long time, make short stops to stretch, you can also change the position of your seat, this will give relief to your spine.",
    "41. Be flexible and open to changes in plans, as something unpredictable can always come up when traveling.",
    "42. Be prepared for lack of phone or internet coverage in some places.",
    "43. Remember to rest and relax, not just travel non-stop.",
    "44. Before traveling to a country, download offline maps not only of the destination country but also of those you will be passing through.",
    "45. install appropriate apps to find places to sleep (GoogleMaps, Park4Night, etc.).",
    "46. Always carry enough cash or debit card to pay for travel expenses.",
    "47. Divide larger amounts of cash into several smaller ones and stash them in unobtrusive places. The car glove box is the first thing a potential thief will check.",
    "48. Set a good example. If you see trash left by others, try to pick it up and dispose of it in an appropriate place.",
    "49. Buy travel insurance, assistance, towing.",
    "50. Take care of your safety and the safety of your loved ones, always wear a seat belt and avoid driving after drinking alcohol.",
    "51. Take advantage of opportunities to meet new people and experience different cultures by sharing your experiences with others.",
    "52. Be ready for unforeseen expenses, such as car repairs or buying extra fuel.",
    "53. If you don't have an idea of a place to stop for the night, you can ask about the possibility of stopping at a gas station, for example.",
    "54. Be prepared for different road conditions, such as rocky roads, high mountains or roads with sharp curves.",
    "55. Observe the rules for entering national parks or other protected areas so that you don't put nature in harm's way and yourself in additional expense.",
    "56. Be patient when driving and encounter difficult roads, a crowd of people or car problems that may cause delays in your trip.",
    "57. Souvenirs. Be sure to leave some room for items purchased on your trip.",
    "58. Explore not only new places, try local cuisine as well. Open yourself up to new flavors, you may come back from your trip with a new favorite dish.",
    "59. Follow camping rules, such as leaving the site in the condition you found it, and obeying rules about campfires and barbecues.",
    "60. avoid environmental pollution, try using eco-friendly cosmetics",
    "61. you can minimize water consumption by using public sources, including toilets and showers.",
    "62. Try to learn new skills such as campfire cooking, climbing or surfing to broaden your horizons and enjoy your trip more.",
    "63. Small towns or villages in the area where you are currently staying may be a better attraction for you than a crowded tourist city.",
    "64. It's a good idea to always have basic foodstuffs such as flour, yeast, sugar and salt in your car.",
    "65. Learn from your mistakes and don't stop experimenting with different solutions.",
    "66. Remember to use your free time to develop your interests and passions, whether through reading, learning languages or creating art.",
    "67. Enjoy nature and allow yourself moments of reflection and meditation to gain new perspectives on your life and goals.",
    "68. Be ready for unexpected challenges and situations, and that it won't always be easy.",
    "69. If you are traveling alone, stay sober, you don't know if the Police will not come and order you to repark your car.",
    "70. Don't get into a discussion with local police and residents. Respect them.",
    "71. Be grateful for every moment and every experience that meets you on your journey, and for every person who comes into your life and shares their stories and wisdom with you.",
    "72. remember that traveling by car involves some risk, so always be alert and careful on the road.",
    "73. Take care of your relationships with family and friends by keeping in touch with them and sharing your experiences.",
    "74. Be open to learning and personal development, using your time in the car to listen to audiobooks, podcasts or learn new skills.",
    "75. Watch out for pickpockets on public transportation. Always keep an eye on your luggage.",
    "76. If you're traveling with a pet make sure it's at the right temperature and has access to drinking water.",
    "77. Replace chemical toiletries with eco-friendly ones such as sachets or septic tank tablets.",
    "78. Do not leave your hiking equipment (Chairs, table, grill) outside overnight.",
    "79. be humble/be humble to locals and all passersby. Smile! You are part of their daily routine, their place and home grounds.",
    "80. Be kind to locals. Chances are you will need their help if you have an unexpected problem.",
    "81. A drone is a great device for creating travel souvenirs. Remember to keep other people safe and private.",
    "82. If you have a drone, check the current regulations in the country you are in. Observe flight bans in designated areas.",
    "83. If you have a drone, never take off near an airport.",
    "84. Don't obstruct the view from someone's house, restaurant or terrace.",
    "85. If your van/caravan takes up more than one parking space, park elsewhere.",
    "86. read/translate information on signs.",
    "87. Sometimes finding a parking space can be a problem. You can ask locals or the police for a convenient place to stay.",
    "88. Start writing a travel journal, it can be a great souvenir.",
    "89. Take a board game or cards with you, it will add variety to your time during bad weather.",
    "90. ?Approach each day strategically,? Plan shopping, servicing, emptying the toilet and gray water the day before.",
    "91. cooking in an RV/campervan takes much more time than in a stir-fry.",
    "92. Be prepared to clean the car frequently. Stock up on a sweeper or vacuum cleaner.",
    "93. Be prepared for numerous insects, not just mosquitoes. A mosquito net may be only a partial solution.",
    "94. Don't turn on a light in the evening with the door ajar.",
    "95. Before you leave, check the condition of your spare wheel, and you can also get a tire repair kit. This will allow you to reach the nearest vulcanization.",
    "96. Be ready to step out of your comfort zone.",
    "97. If you work remotely, make sure you have a comfortable place to work. A lounger and a beach looks cool only in pictures.",
    "98. Every day is an adventure. Treat it as a good time.",
    "99. If you travel with a pet, keep it close to your car.",
    "100. When there is no coverage on your phone, it is a good idea to have a paper map with you.",
    "101. Weather conditions during a walk can change suddenly, and it is advisable to bring a raincoat that can fit in your pocket.",
    "102. Before traveling, check the validity of your passport and other documents.",
    "103. Get a European Health Insurance Card (EHIC) LINK.",
    "104. Bring a small kettle to boil water for coffee to save time and water.",
    "105. Remember UV sunscreen, in summer, winter and even when you go to the mountains.",
    "106. Make a shopping list you will avoid unnecessary/additional expenses.",
    "107. Don't pack at the last minute, prepare the necessary items at least two days in advance,",
    "108. A bottle of alcohol or other gift is a good idea to give as a thank you for your help?"]
