import Foundation
import Darwin

let rulesListES = [
    "1. Invierte en un buen colchón. Dormir bien es muy importante para tu salud y bienestar.",
    "2. Vale la pena tener una caja de herramientas básica en el coche, incluso si no sabes reparar el vehículo, alguien más podría ayudarte.",
    "3. Prepara una lista de cosas que necesitas llevar antes de cada viaje.",
    "4. Lleva siempre contigo un botiquín de primeros auxilios.",
    "5. Planifica tus viajes con antelación y presta atención a las condiciones meteorológicas.",
    "6. Aprende a utilizar diferentes fuentes de energía: desde paneles solares hasta generadores.",
    "7. Lleva siempre suficiente agua potable contigo.",
    "8. Prueba todos los dispositivos en tu camper o caravana antes del viaje.",
    "9. Aprende cómo funciona el sistema de aguas residuales en tu camper o caravana.",
    "10. Cierra siempre puertas y ventanas cuando salgas del camper o caravana.",
    "11. No olvides hacer mantenimientos y revisiones periódicas de tu camper o caravana.",
    "12. Ten a mano medicamentos esenciales como analgésicos o carbón activado.",
    "13. Revisa el estado técnico de tu vehículo antes del viaje.",
    "14. Si viajas a una zona fría, aunque en destino haga calor, usa neumáticos de invierno.",
    "15. Lleva siempre en el coche una botella de aceite de motor adecuado para tu vehículo.",
    "16. Un camino de difícil acceso suele llevar a un lugar salvaje y maravilloso.",
    "17. Sé respetuoso con los demás: si aparcas entre campers, mantén una distancia adecuada.",
    "18. Si sales a caminar por la tarde, lleva una linterna o un powerbank con cable para el móvil.",
    "19. Si te equivocas de camino, no des la vuelta – déjate llevar por la aventura, pero con sensatez.",
    "20. Si subes una cuesta en segunda marcha, bájala también en segunda.",
    "21. Si viajas solo/a, comparte tu ubicación con tu familia con frecuencia.",
    "22. Si tienes la oportunidad de rellenar agua o vaciar aguas grises o negras, hazlo – puede que el próximo servicio esté lejos.",
    "23. Si viajas con otra persona, acordad cómo comunicaros en caso de separaros.",
    "24. Si no hay una papelera cerca, lleva tu basura contigo.",
    "25. Una manguera larga para el agua siempre es mejor que una corta.",
    "26. Vale la pena tener distintos adaptadores para grifos – nunca sabes con qué te encontrarás.",
    "27. ¿El camino hacia donde vas a dormir es cuesta abajo? Revisa el pronóstico del tiempo – si va a llover, busca otro sitio, podrías quedarte atascado por la mañana.",
    "28. Nunca te detengas si alguien te hace señas – ni en carretera ni en autopista.",
    "29. Ahorra agua, gas y electricidad.",
    "30. Al empacar para un viaje largo, no lleves cosas innecesarias – con el tiempo verás que no las necesitas.",
    "31. Si has encontrado un lugar genial en Google Maps o Park4Night, revisa si hay otras atracciones cerca – podría dejar de estar disponible pronto.",
    "32. Si llegas a un sitio y no te sientes seguro, cambia de ubicación.",
    "33. Si no te sientes seguro donde estás, busca otros campers – en grupo estarás más protegido.",
    "34. Encuentra un lugar seguro en el vehículo para objetos de valor – puedes instalar una caja fuerte pequeña o una caja metálica con candado. Asegúrate de protegerla bien contra robos.",
    "35. Respeta el entorno por el que viajas – sigue normas ecológicas como mantener limpio el lugar y separar los residuos.",
    "36. Disfruta la libertad y la aventura que te ofrece el vanlife. Que tu viaje sea una experiencia inolvidable. ¡Vive el momento!",
    "37. Respeta las culturas y tradiciones locales.",
    "38. Respeta las normas de tráfico del país por el que viajas para evitar multas.",
    "39. Reduce el uso de productos plásticos desechables como vasos y cubiertos.",
    "40. Durante viajes largos, haz pausas cortas para estirarte – también puedes cambiar la posición del asiento para aliviar la espalda.",
    "41. Sé flexible y abierto/a a cambios de planes – siempre pueden surgir imprevistos en el camino.",
    "42. Prepárate para zonas sin señal de móvil o acceso a internet.",
    "43. Recuerda descansar y relajarte, no solo viajar sin parar.",
    "44. Antes de viajar a otro país, descarga mapas offline – tanto del destino como de la ruta.",
    "45. Instala aplicaciones útiles para encontrar lugares donde dormir (Google Maps, Park4Night, etc.).",
    "46. Lleva siempre suficiente efectivo o una tarjeta de pago para cubrir los gastos del viaje.",
    "47. Divide grandes cantidades de dinero en partes pequeñas y escóndelas en sitios poco obvios – la guantera es lo primero que revisa un ladrón.",
    "48. Da un buen ejemplo – si ves basura dejada por otros, recógela y tírala en un lugar adecuado.",
    "49. Contrata un seguro de viaje, asistencia y remolque.",
    "50. Cuida tu seguridad y la de tus seres queridos.",
    "51. Aprovecha la oportunidad de conocer gente nueva y descubrir otras culturas.",
    "52. Prepárate para gastos inesperados como una reparación del coche o combustible adicional.",
    "53. Si no sabes dónde dormir, pregunta si puedes pasar la noche – por ejemplo, en una gasolinera.",
    "54. Prepárate para diferentes condiciones de carretera, como caminos con piedras, montañas altas o curvas cerradas.",
    "55. Respeta las normas de entrada a parques nacionales o áreas protegidas para no dañar la naturaleza ni recibir multas.",
    "56. Sé paciente – durante el viaje puedes encontrar caminos difíciles, mucha gente o problemas técnicos que retrasen tu ruta.",
    "57. Deja espacio para recuerdos – seguro compras algo durante el viaje.",
    "58. Descubre no solo lugares nuevos, también prueba la cocina local. Ábrete a nuevos sabores – quizás regreses con un nuevo plato favorito.",
    "59. Sigue las normas del camping – deja el lugar como lo encontraste y respeta las normas sobre fuegos y barbacoas.",
    "60. Evita contaminar el entorno – usa cosméticos y productos de limpieza ecológicos.",
    "61. Puedes reducir el consumo de agua utilizando fuentes públicas, como baños y duchas.",
    "62. Intenta aprender nuevas habilidades, como cocinar al fuego, escalar o hacer surf, para ampliar tus horizontes y disfrutar más del viaje.",
    "63. Los pueblos pequeños en los alrededores pueden ser más atractivos que las ciudades turísticas llenas de gente.",
    "64. Siempre es útil tener productos alimenticios básicos en el vehículo, como harina, levadura, azúcar o sal.",
    "65. Aprende de tus errores y sigue experimentando con distintas soluciones.",
    "66. Aprovecha tu tiempo libre para desarrollar tus intereses y pasiones – lee, aprende idiomas o crea arte.",
    "67. Disfruta de la naturaleza y permítete momentos de reflexión y meditación para obtener nuevas perspectivas sobre tu vida y tus metas.",
    "68. Prepárate para desafíos y situaciones inesperadas – no siempre será fácil.",
    "69. Si viajas solo/a, mantente sobrio/a – no sabes si la policía podría llegar y pedirte que cambies de lugar.",
    "70. No entres en discusiones con la policía local ni con los residentes – muéstrales respeto.",
    "71. Agradece cada momento y experiencia que encuentres en tu camino, y a cada persona que comparta contigo su historia y sabiduría.",
    "72. Recuerda que viajar en coche conlleva ciertos riesgos – mantente siempre alerta y prudente en la carretera.",
    "73. Cuida tus relaciones con la familia y amigos manteniéndote en contacto y compartiendo tus experiencias.",
    "74. Mantente abierto/a al aprendizaje y al crecimiento personal – utiliza el tiempo en el coche para escuchar audiolibros, podcasts o aprender nuevas habilidades.",
    "75. Ten cuidado con los carteristas en el transporte público – vigila siempre tu equipaje.",
    "76. Si viajas con una mascota, asegúrate de que tenga una temperatura adecuada y acceso al agua potable.",
    "77. Cambia los productos químicos del inodoro por opciones ecológicas – como sobres o pastillas para depósitos.",
    "78. No dejes el equipo de camping (sillas, mesa, barbacoa) fuera durante la noche.",
    "79. Sé humilde con los locales y los transeúntes – sonríe, eres parte de su rutina diaria y entorno.",
    "80. Sé amable con los locales – puede que necesites su ayuda en una situación inesperada.",
    "81. Un dron es una excelente herramienta para crear recuerdos de viaje. Asegúrate de respetar la seguridad y privacidad de los demás.",
    "82. Si tienes un dron, revisa la normativa del país en el que estás y respeta las zonas restringidas de vuelo.",
    "83. Si tienes un dron, nunca lo lances cerca de un aeropuerto.",
    "84. No bloquees con tu vehículo la vista desde una casa, restaurante o terraza.",
    "85. Si tu furgoneta o autocaravana ocupa más de un espacio de aparcamiento, busca otro lugar.",
    "86. Lee o traduce la información en las señales.",
    "87. A veces encontrar sitio para aparcar puede ser difícil – pregunta a los locales o a la policía por un lugar adecuado para pasar la noche.",
    "88. Empieza a escribir un diario de viaje – puede ser un gran recuerdo.",
    "89. Lleva un juego de mesa o una baraja de cartas – será útil cuando haga mal tiempo.",
    "90. Planifica las compras, la carga de agua y el vaciado del inodoro y aguas grises un día antes.",
    "91. Ten en cuenta que cocinar en una camper o furgoneta lleva mucho más tiempo que en casa.",
    "92. Prepárate para limpiar con frecuencia el vehículo – lleva una escoba o una aspiradora.",
    "93. Prepárate para la presencia de muchos insectos – no solo mosquitos. Una mosquitera puede no ser suficiente.",
    "94. No enciendas la luz por la noche si tienes las puertas entreabiertas.",
    "95. Antes de salir, revisa el estado de la rueda de repuesto y lleva un kit de reparación de neumáticos – te puede ayudar a llegar al taller más cercano.",
    "96. Prepárate para salir de tu zona de confort.",
    "97. Si trabajas en remoto, asegúrate de tener un espacio cómodo para trabajar – una tumbona en la playa se ve bien solo en fotos.",
    "98. Cada día es una aventura – disfrútala como un juego.",
    "99. Si viajas con una mascota, mantenla cerca del vehículo.",
    "100. Cuando no tengas cobertura en el teléfono, es útil tener un mapa en papel contigo.",
    "101. Las condiciones climáticas pueden cambiar repentinamente durante un paseo. Vale la pena llevar un impermeable que quepa en el bolsillo.",
    "102. Antes del viaje, verifica la validez del pasaporte y otros documentos.",
    "103. Solicita la Tarjeta Sanitaria Europea (TSE).",
    "104. Lleva un hervidor pequeño para preparar café – ahorrarás tiempo y agua.",
    "105. No olvides el protector solar – en verano, en invierno e incluso en caminatas por la montaña.",
    "106. Haz una lista de la compra – evitarás gastos innecesarios.",
    "107. No hagas la maleta a última hora – prepara todo al menos dos días antes.",
    "108. Una botella de alcohol o un pequeño obsequio es una buena forma de agradecer la ayuda.",
    "109. Si estás cerca de una gasolinera y se enciende la reserva, reposta – la próxima puede estar muy lejos.",
    "110. Comparte tus experiencias con los demás.",
    "111. Si tienes la oportunidad de llenar agua o vaciar el inodoro, hazlo – igual que con el combustible, nunca sabes cuándo será la próxima vez.",
    "112. Si viajas con alguien, especialmente fuera de la UE, acordad cómo comunicaros en caso de no tener internet.",
    "113. Si tienes un mal presentimiento sobre el estado de tu vehículo, no lo ignores.",
    "114. Al reparar el vehículo, empieza revisando las piezas más caras. Si piensas reparar en un país más barato, ten en cuenta que puede costarte el doble.",
    "115. Si tienes un mal presentimiento sobre el lugar donde piensas dormir, busca otro – no tientes al destino.",
    "116. No pospongas el desayuno – durante el día pasan muchas cosas, y el primer plato a las 19:00 normalmente se llama cena.",
    "117. Si el tiempo no coincide con los kilómetros recorridos, considera cambiar de lugar – puede significar que el camino está en mal estado o es todo off-road.",
    "118. Si Google Maps indica mal el camino, revísalo en otra aplicación.",
    "119. Si algo se rompió y luego “se arregló solo”, sigue estando roto.",
    "120. Bridas, cinta americana y WD-40 – tenlos siempre a mano.",
    "121. Si la fiesta de anoche se alargó, espera antes de conducir – o acércate a una comisaría y pide una prueba de alcoholemia.",
    "122. Si estás en la montaña y ha nevado, espera a que pase la quitanieves. Conducir detrás de ella te facilitará el camino.",
    "123. Siempre que salgas de viaje, lleva tu pasaporte – nunca sabes a dónde te llevará la aventura.",
    "124. Familiarízate con las normas de tráfico y el estilo de conducción de los conductores locales.",
    "125. Verifica cuál es el equipamiento obligatorio del vehículo en el país al que viajas o por el que pasas (chalecos, extintor, triángulo, etc.).",
    "126. Lleva contigo la Carta Verde si viajas en coche al extranjero.",
    "127. Si es posible, contrata un seguro adicional válido en el país al que vas.",
    "128. Si viajas fuera de la Unión Europea, consulta los requisitos del país en cuestión.",
    "129. Verifica si necesitas vacunas para entrar al país al que viajas.",
    "130. Pregunta a los habitantes locales por atracciones en los alrededores.",
    "131. Infórmate sobre la cultura del país – por ejemplo, los gestos locales.",
    "132. Lleva siempre puesto el cinturón de seguridad – puede salvarte la vida.",
    "133. Evita conducir después de beber alcohol, incluso si solo has tomado una cerveza.",
    "134. Vale la pena tener una fuente de luz adicional en el coche – como una lámpara LED a pilas o un powerbank. Puede sacarte de un apuro en la oscuridad.",
    "135. Si pasas la noche al lado de la carretera, elige un lugar bien iluminado y, si es posible, vigilado.",
    "136. Aprende algunas frases básicas en el idioma local – basta con “gracias”, “por favor” y “¿dónde está…?”.",
    "137. En días calurosos, cubre las ventanas del lado del sol – esto bajará bastante la temperatura dentro.",
    "138. Lleva siempre un cargador de coche – el móvil no es solo para comunicar, también sirve como GPS, cámara y linterna.",
    "139. Si vas a un lugar nuevo, revisa las opiniones de otros viajeros – no todo lo que se ve bonito en fotos es seguro.",
    "140. Ventila el vehículo con frecuencia – especialmente si viajas con animales.",
    "141. Apunta tus gastos diarios – incluso las pequeñas cantidades se acumulan rápidamente.",
    "142. Si duermes cerca del mar, revisa el pronóstico de las mareas – el agua puede acercarse bastante por la noche.",
    "143. Ten siempre preparado un plan B para dormir – puede que el sitio que querías esté ocupado o no sea seguro.",
    "144. Lleva fusibles de repuesto – uno de ellos puede ser la causa de que la nevera no funcione.",
    "145. En días fríos, cubre las ventanas desde dentro – una manta térmica o una lámina reflectante realmente ayudan.",
    "146. Si haces un viaje largo, dedica al menos un día a tareas de mantenimiento, limpieza y lavandería.",
    "147. Al entrar en lugares religiosos, viste adecuadamente y sé respetuoso – incluso si solo estás de paso.",
    "148. Recuerda que algunos países tienen enchufes diferentes – lleva un adaptador.",
    "149. Ten una bolsa con ropa de cambio al alcance – el clima puede cambiar en cualquier momento.",
    "150. Si pierdes algo o te lo dejas, vuelve a buscarlo lo antes posible – cada hora que pasa reduce tus posibilidades.",
    "151. Aprende procedimientos básicos en caso de incendio o inundación – los segundos son importantes.",
    "152. Si usas cocina de gas, controla el nivel y cierra la válvula tras cocinar.",
    "153. No tengas prisa. A veces vale la pena quedarse un día más en un sitio que te transmite paz y buena energía.",
    "154. Si planeas quedarte más tiempo en un lugar, aparca de forma que el sol de la mañana ilumine la cocina – cocinar será más agradable.",
    "155. Prueba cualquier equipo nuevo antes de salir – nada peor que una parrilla que no funciona cuando tienes hambre.",
    "156. Guarda los sitios buenos que encuentres – aunque no te quedes, tal vez regreses o se los recomiendes a otros.",
    "157. Lleva un registro del consumo de combustible – te ayudará a evaluar el estado del vehículo.",
    "158. Ten copias físicas de tus documentos importantes – en caso de robo o avería del móvil, pueden ser clave.",
    "159. No estaciones demasiado cerca de otros vehículos – respeta el espacio de todos.",
    "160. Evita conducir de noche si puedes – es más fácil cometer errores y más difícil conseguir ayuda.",
    "161. Al menos una vez por semana, limpia bien el interior – viajar no es excusa para vivir en el desorden.",
    "162. Guarda las llaves de repuesto en un lugar distinto a las originales – una caja magnética bajo el coche puede ser útil.",
    "163. Si aparcas en la naturaleza, revisa si hay signos de animales salvajes – no querrás despertarte junto a un jabalí.",
    "164. En zonas húmedas, usa absorbentes de humedad o abre las ventanas si hace buen tiempo.",
    "165. No dejes comida fuera – las hormigas y avispas pueden aparecer rápidamente.",
    "166. Lleva una libreta con códigos, datos de campings y otros apuntes útiles – no todo está en internet.",
    "167. Antes de arrancar, haz una revisión rápida del vehículo – que todo esté cerrado, desconectado y seguro.",
    "168. Compra en mercados locales – es más barato y más sabroso.",
    "169. Usa un parasol en el parabrisas – ayuda a mantener fresco el interior.",
    "170. En zonas con muchos insectos, usa repelentes naturales – como aceite de limón, lavanda o eucalipto.",
    "171. Guarda todas las herramientas en un solo lugar fácil de acceder – una caja de herramientas es tu amiga.",
    "172. Antes de dormir, verifica que el suelo esté nivelado – una leve inclinación puede arruinar tu descanso.",
    "173. No dejes dispositivos electrónicos al sol – pueden sobrecalentarse rápidamente.",
    "174. Haz fotos de tus documentos, matrícula y número VIN – podrían ser útiles en el extranjero.",
    "175. Asegúrate de que los powerbanks estén cargados – son esenciales si se agota la batería principal.",
    "176. Deja una nota con tu contacto en un lugar visible – alguien puede necesitar comunicarse contigo.",
    "177. En días calurosos, cocina por la mañana o por la noche – el mediodía es para descansar.",
    "178. Mantén pequeñas rutinas durante el viaje – estiramientos, café, 15 minutos de orden – ayudan a mantener el equilibrio.",
    "179. Enseña a tu mascota comandos básicos – por seguridad.",
    "180. Intenta dormir con la cabeza ligeramente elevada – ayuda a respirar mejor.",
    "181. Que algo funcione hoy no significa que funcione mañana – prepárate para averías.",
    "182. Siempre revisa los frenos antes de recorrer largos trayectos de montaña – más vale prevenir.",
    "183. Habla con los locales – son los mejores guías que encontrarás.",]
