// Created by Mateusz Mlynarski
// All rights reserved

import Foundation

let rulesListES: [String] = [
  "1. Invierte en un buen colchón. Dormir es muy importante para tu salud y bienestar.",
  "2. Conviene llevar en el coche una maleta básica de herramientas – incluso si tú mismo no sabes reparar el coche, alguien puede ayudarte.",
  "3. Prepara una lista de cosas que debes llevar contigo antes de cada viaje.",
  "4. Lleva siempre contigo un botiquín de primeros auxilios.",
  "5. Planifica tus viajes con antelación y presta atención a las condiciones meteorológicas.",
  "6. Aprende a usar distintas fuentes de energía. Desde paneles solares hasta un generador.",
  "7. Lleva siempre contigo una cantidad suficiente de agua potable.",
  "8. Prueba todos los dispositivos en la autocaravana o remolque antes de salir.",
  "9. Aprende cómo funciona el sistema de evacuación de aguas residuales en tu autocaravana o remolque.",
  "10. Cierra siempre puertas y ventanas cuando dejes la autocaravana o el remolque.",
  "11. Recuerda hacer el mantenimiento y las revisiones periódicas de la autocaravana o del remolque.",
  "12. Abastécete de medicamentos necesarios, como analgésicos o carbón activado.",
  "13. Antes de salir, revisa el estado técnico de tu vehículo.",
  "14. Si sales en invierno, aunque en el lugar sea verano, conduce con neumáticos de invierno o para todo el año.",
  "15. Lleva siempre en el coche una botella de aceite de motor indicado para tu vehículo.",
  "16. Un camino de acceso difícil suele esconder al final un lugar estupendo y salvaje.",
  "17. Cuida de los demás. Si aparcas entre autocaravanas, mantén una distancia adecuada.",
  "18. Si sales a pasear a última hora de la tarde, lleva una linterna o un powerbank con cable para el teléfono.",
  "19. Si te equivocas de camino, no des la vuelta. Déjate llevar por la aventura, pero por supuesto con prudencia.",
  "20. Si subes una cuesta en segunda marcha, baja también en segunda marcha.",
  "21. Si viajas solo, comparte a menudo tu ubicación con tu familia más cercana.",
  "22. Si tienes la posibilidad de rellenar agua y vaciar el agua gris o negra, hazlo, porque puede resultar que el servicio más cercano no quede de camino.",
  "23. Si viajas con otra persona, acordad siempre un método de comunicación por si os perdéis o os separáis.",
  "24. Si cerca no hay una papelera, llévate la basura contigo.",
  "25. Una manguera larga para llenar agua siempre es mejor que una corta.",
  "26. Conviene llevar distintos adaptadores que se enroscan en las válvulas de agua; nunca sabes qué te encontrarás en el lugar.",
  "27. ¿El camino al lugar donde piensas dormir va cuesta abajo? Revisa la previsión del tiempo; si se anuncia lluvia, elige otro sitio, porque por la mañana puedes tener problemas para salir.",
  "28. Nunca te detengas cuando alguien te haga señas. Tanto en una carretera normal como en la autopista.",
  "29. Ahorra agua, gas y electricidad.",
  "30. Al hacer la maleta para un viaje largo, no lleves cosas innecesarias; con el tiempo te darás cuenta de que no las necesitas en absoluto.",
  "31. Si encontraste un lugar genial en Google Maps o Park4Night, comprueba si cerca hay otros lugares donde se pueda pasar la noche. Puede resultar que ese gran lugar ya no esté disponible.",
  "32. Si llegaste al lugar y no te sientes seguro allí, cambia de ubicación.",
  "33. Si no te sientes seguro en el lugar donde estás, busca otras autocaravanas. En grupo será más seguro.",
  "34. Encuentra en el coche un lugar para las cosas de valor. Puedes instalar una pequeña caja fuerte o una caja metálica con cerradura. Recuerda protegerlas adecuadamente contra el robo.",
  "35. Cuida el entorno en el que viajas; respeta las normas ecológicas, como mantener el lugar limpio y separar la basura.",
  "36. Disfruta de la libertad y la aventura que ofrece el van life. Que el viaje se convierta para ti en una experiencia inolvidable que quedará en tu memoria para siempre. ¡Vive este momento!",
  "37. Recuerda respetar las culturas y tradiciones locales.",
  "38. Respeta las normas de tráfico del país por el que viajas para evitar una multa.",
  "39. Reduce el uso de objetos de plástico de un solo uso, como vasos o cubiertos.",
  "40. Durante un viaje largo, haz paradas cortas para estirarte. También puedes cambiar la posición del asiento, lo que aliviará tu columna.",
  "41. Sé flexible y abierto a cambios de planes, porque en el viaje siempre puede aparecer algo imprevisible.",
  "42. Prepárate para la falta de cobertura de teléfono o de internet en algunos lugares.",
  "43. Recuerda descansar y relajarte, y no solo viajar sin parar.",
  "44. Antes de viajar a un país, descarga mapas sin conexión – tanto del país de destino como de las rutas de viaje.",
  "45. Instala aplicaciones adecuadas para encontrar lugares para dormir (Google Maps, Park4Night, Grupa Biwakowa, Stay Free, etc.).",
  "46. Lleva siempre contigo suficiente efectivo o tarjetas de pago para poder cubrir los gastos del viaje.",
  "47. Divide una suma grande de efectivo en varias más pequeñas y repártelas en lugares poco obvios. La guantera es el primer lugar que revisará un posible ladrón.",
  "48. Da buen ejemplo. Si ves basura dejada por otros, recógela y tírala en el lugar adecuado.",
  "49. Contrata un seguro de viaje, asistencia y remolque.",
  "50. Cuida tu seguridad y la seguridad de tus seres queridos.",
  "51. Aprovecha la posibilidad de conocer gente nueva y descubrir distintas culturas.",
  "52. Sé consciente de gastos imprevistos, como una reparación del coche o una visita al médico.",
  "53. Si no se te ocurre un lugar para pasar la noche, pregunta por la posibilidad de aparcar – por ejemplo, en una gasolinera.",
  "54. Prepárate para distintas condiciones de carretera, como caminos pedregosos, montañas altas o rutas con curvas cerradas.",
  "55. Respeta las normas de entrada a parques nacionales u otras zonas protegidas para no exponer la naturaleza a daños y a ti mismo a gastos adicionales.",
  "56. Sé paciente. Al conducir puedes encontrarte con carreteras difíciles, aglomeraciones o problemas técnicos que pueden retrasar el viaje.",
  "57. Al hacer la maleta, recuerda dejar algo de espacio para las cosas compradas durante el viaje.",
  "58. Descubre no solo lugares nuevos, sino también prueba la cocina local. Ábrete a nuevos sabores y quizá vuelvas del viaje con un nuevo plato favorito.",
  "59. Respeta las normas de camping. Deja el lugar tal como lo encontramos y respeta las normas sobre hogueras y barbacoas.",
  "60. Evita contaminar el medio ambiente. Usa cosméticos y productos de limpieza ecológicos.",
  "61. Puedes minimizar el consumo de agua usando fuentes públicas, incluidas aseos y duchas.",
  "62. Intenta aprender nuevas habilidades, como cocinar en una hoguera, escalar o surfear, para ampliar tus horizontes y disfrutar más del viaje.",
  "63. Los pueblos pequeños o aldeas de la zona en la que estás pueden ser más atractivos que las ciudades turísticas abarrotadas.",
  "64. Conviene tener siempre en el coche productos básicos de alimentación, como harina, levadura, azúcar o sal.",
  "65. Aprende de los errores y no dejes de experimentar con diferentes soluciones.",
  "66. Recuerda aprovechar el tiempo libre para desarrollar tus intereses y pasiones. Lee, aprende idiomas extranjeros o crea arte.",
  "67. Disfruta de la naturaleza y permítete momentos de reflexión y meditación para obtener nuevas perspectivas sobre tu vida y tus objetivos.",
  "68. Estate preparado para desafíos y situaciones inesperadas. No siempre será fácil.",
  "69. Si viajas solo/sola, mantente sobrio. No sabes si la policía vendrá y te ordenará cambiar el lugar de estacionamiento.",
  "70. No entres en discusiones con la policía local ni con los residentes. Muéstrales respeto, porque tú eres un invitado en su país.",
  "71. Sé agradecido por cada momento y experiencia que encuentres en tu camino, y por cada persona que comparta contigo su historia y sabiduría.",
  "72. Recuerda que viajar en coche conlleva cierto riesgo. Mantente siempre atento y prudente en la carretera.",
  "73. Cuida las relaciones con la familia y los amigos, manteniendo el contacto y compartiendo tus experiencias.",
  "74. Sé abierto al aprendizaje y al desarrollo personal. Aprovecha el tiempo en el coche para escuchar audiolibros, podcasts o aprender nuevas habilidades.",
  "75. Ten cuidado con los carteristas en el transporte público; mantén siempre un ojo en tu equipaje.",
  "76. Si viajas con una mascota, asegúrate de que tenga una temperatura adecuada y acceso a agua potable.",
  "77. Sustituye los productos químicos para el WC por ecológicos. Por ejemplo, sobres o tabletas para depósitos.",
  "78. No dejes por la noche el equipo de camping (sillas, mesa, barbacoa) fuera.",
  "79. Sé humilde frente a los locales y transeúntes; sonríe, porque eres parte de su rutina diaria y su entorno.",
  "80. Sé amable con los locales. Puede ocurrir que necesites su ayuda en una situación inesperada.",
  "81. Un dron es una herramienta excelente para crear recuerdos del viaje. Recuerda mantener la seguridad y la privacidad de otras personas.",
  "82. Si tienes un dron, comprueba las normas vigentes en el país en el que estás y respeta las prohibiciones de vuelo en zonas restringidas.",
  "83. Si tienes un dron, nunca despegues cerca de un aeropuerto.",
  "84. No tapes con el coche la vista desde una casa, un restaurante o una terraza.",
  "85. Si tu furgoneta o autocaravana ocupa más de una plaza de aparcamiento, aparca en otro lugar.",
  "86. Lee o traduce la información en las señales.",
  "87. A veces encontrar una plaza de aparcamiento puede ser un problema. Pregunta a los locales o a la policía por un lugar adecuado para pasar la noche.",
  "88. Empieza a escribir un diario de viaje; puede ser un gran recuerdo.",
  "89. Llévate un juego de mesa o cartas. Harán el tiempo más ameno durante el mal tiempo.",
  "90. Planifica las compras, el llenado de agua y el vaciado del WC y del agua gris el día anterior.",
  "91. Ten en cuenta que cocinar en una autocaravana o campervan lleva mucho más tiempo que en un piso.",
  "92. Prepárate para limpiar el coche con frecuencia. Consigue una escobilla o una aspiradora.",
  "93. Prepárate para la presencia de muchos insectos, no solo mosquitos. Una mosquitera puede ser solo una solución parcial.",
  "94. No enciendas la luz por la noche con la puerta entreabierta.",
  "95. Antes de salir, revisa la rueda de repuesto y consigue un kit de reparación de neumáticos. Te permitirá llegar a la vulcanizadora más cercana.",
  "96. Estate dispuesto a salir de tu zona de confort.",
  "97. Si trabajas en remoto, asegúrate de tener un lugar de trabajo cómodo. Una tumbona y la playa se ven bien solo en las fotos.",
  "98. Cada día es una aventura. Trátala como una buena diversión.",
  "99. Si viajas con una mascota, mantenla cerca del coche.",
  "100. Cuando el teléfono se quede sin cobertura, conviene llevar un mapa en papel.",
  "101. Las condiciones meteorológicas durante un paseo pueden cambiar de repente. Conviene llevar un impermeable que quepa en el bolsillo.",
  "102. Antes del viaje, comprueba la validez del pasaporte y de otros documentos.",
  "103. Tramita la Tarjeta Sanitaria Europea (EKUZ).",
  "104. Consigue una pequeña taza metálica para hervir agua para café o té.",
  "105. Recuerda usar crema con filtro UV en verano, pero también en invierno.",
  "106. Haz una lista de compras; así evitarás gastos innecesarios o adicionales.",
  "107. No hagas la maleta a última hora. Prepara lo necesario al menos dos días antes.",
  "108. Una botella de alcohol u otra cosa de tu país es una buena idea para agradecer la ayuda.",
  "109. Si estás cerca de una gasolinera y se enciende la reserva, reposta. La siguiente estación puede estar demasiado lejos.",
  "110. Comparte tus experiencias con otros.",
  "111. Cuando surja la ocasión de llenar agua o vaciar el WC, ¡hazlo! Igual que al repostar combustible, nunca sabes cuándo aparecerá la siguiente oportunidad.",
  "112. Si viajas con alguien, especialmente en países fuera de la UE, conviene acordar un método de comunicación en caso de no tener internet.",
  "113. Si tienes malas sensaciones sobre el estado de tu vehículo, no las ignores.",
  "114. Al reparar el coche, empieza por los elementos más caros. Si planeas reparaciones en un país más barato, recuerda que puede costarte el doble.",
  "115. Si tienes malas sensaciones sobre el lugar donde piensas pasar la noche, busca otro.",
  "116. No pospongas el desayuno para más tarde. Durante el día pasan muchas cosas, y la primera comida, a las 19:00, suele llamarse cena.",
  "117. Si el tiempo no se corresponde con la cantidad de kilómetros recorridos, considera cambiar de sitio – puede significar que la carretera es de muy mala calidad o que es off-road.",
  "118. Si Google Maps indica mal la ruta, conviene comprobarla en otra aplicación.",
  "119. Si algo se estropeó y luego se arregló solo, significa que sigue estando averiado.",
  "120. Ten siempre a mano bridas, cinta gris y WD-40.",
  "121. Si la fiesta de ayer se alargó, espera antes de ponerte al volante o ve a una comisaría y pide una prueba de alcoholemia.",
  "122. Si estás en la montaña y ha caído nieve, espera a que aparezca la quitanieves. Ve detrás de ella; facilitará mucho el camino.",
  "123. Si sales a algún sitio, lleva siempre contigo el pasaporte. Nunca sabes adónde te llevará la aventura.",
  "124. Infórmate sobre las normas de circulación y la cultura de conducción de los conductores locales.",
  "125. Comprueba cuál es el equipamiento obligatorio del coche en el país al que vas y por los que atraviesas (p. ej., chalecos, extintor, triángulo).",
  "126. Recuerda llevar la Carta Verde cuando viajes al extranjero en coche.",
  "127. Si es posible, contrata un seguro adicional válido en el país al que vas.",
  "128. Si planeas viajar fuera de la Unión Europea, comprueba los requisitos vigentes en ese país.",
  "129. Comprueba si en el país al que vas se requieren vacunas.",
  "130. Pregunta a los residentes locales por atracciones en la zona.",
  "131. Familiarízate con la cultura del país, por ejemplo, con los gestos locales.",
  "132. Ponte siempre el cinturón de seguridad. Puede salvarte la vida.",
  "133. Evita conducir después de consumir alcohol, incluso después de una sola cerveza.",
  "134. Conviene tener en el coche una fuente de luz adicional, por ejemplo, una lámpara LED a pilas o un powerbank. Puede salvar la situación durante una avería al anochecer.",
  "135. Si te detienes a pasar la noche junto a la carretera, elige lugares bien iluminados y vigilados.",
  "136. Aprende algunas frases básicas en el idioma local. Bastan “gracias”, “por favor” y “¿dónde está…?”.",
  "137. En días calurosos, cubre las ventanas del lado del sol. Eso reduce significativamente la temperatura dentro del vehículo.",
  "138. Lleva siempre a mano un cargador de coche. El teléfono no es solo contacto con el mundo, sino también GPS, cámara y linterna.",
  "139. Si vas a un lugar nuevo, revisa antes las opiniones de otros viajeros. No todo lo que se ve bonito en las fotos es seguro.",
  "140. Recuerda ventilar el coche con frecuencia, especialmente si llevas una mascota.",
  "141. Anota tus gastos a diario; incluso pequeñas cantidades pueden sumarse rápidamente.",
  "142. Si duermes cerca del mar, revisa la previsión de mareas. Por la noche el agua puede acercarse mucho más.",
  "143. Ten siempre preparado un plan B para dormir. A veces el lugar puede estar ocupado o ser poco amigable.",
  "144. Consigue un juego de fusibles. Uno de ellos puede decidir si la nevera funciona o no.",
  "145. En días fríos, cubre las ventanas por dentro. La lámina térmica o una manta que refleje el calor realmente funciona.",
  "146. Si viajas más tiempo, de vez en cuando haz un “día de servicio”. Revisión técnica, lavandería, orden.",
  "147. Cuando entres en lugares de culto religioso, mantén una vestimenta adecuada y respeto, incluso si es solo una visita rápida.",
  "148. Recuerda que algunos países tienen normas diferentes para los enchufes eléctricos. Consigue un adaptador universal.",
  "149. Mantén la bolsa con ropa de cambio accesible. Un cambio repentino del tiempo puede sorprender.",
  "150. Si pierdes o dejas algo, vuelve a por ello lo antes posible. Con cada hora, las probabilidades disminuyen.",
  "151. Aprende procedimientos básicos en caso de incendio o inundación del coche. Los segundos importan.",
  "152. Si tienes una cocina de gas, controla el nivel de gas y cierra siempre la bombona después de cocinar.",
  "153. No te apresures. A veces vale la pena pasar un día más en un lugar que te da calma y buena energía.",
  "154. Si planeas quedarte en un lugar más tiempo, coloca el coche para que el sol de la mañana te dé hacia la cocina y cocinar será más agradable.",
  "155. Antes de salir, prueba el equipo nuevo; nada frustra tanto como una barbacoa que no funciona y estás antes de comer.",
  "156. Anota lugares chulos; aunque no te quedes, puedes volver otro día o recomendárselos a amigos.",
  "157. Lleva un registro del consumo de combustible, p. ej., la app Drivvo. Te ayudará a evaluar si el coche funciona correctamente.",
  "158. Asegúrate de tener una copia física de documentos importantes. En caso de robo o avería del teléfono pueden ser útiles.",
  "159. No aparques demasiado cerca de otros vehículos. Date espacio a ti y a los demás.",
  "160. Si puedes, evita conducir de noche. Es más fácil cometer errores y más difícil conseguir ayuda si hace falta.",
  "161. Al menos una vez a la semana limpia a fondo el interior. Viajar no es motivo para vivir en el caos.",
  "162. Deja una llave de repuesto en otro lugar que la original, por ejemplo, pegada con un imán bajo el coche.",
  "163. Si aparcas en la naturaleza, comprueba si el lugar no es un hábitat de animales salvajes. No quieres despertarte al lado de un jabalí.",
  "164. ¿Humedad alta? Usa absorbentes de humedad o abre las ventanas con buen tiempo.",
  "165. No dejes comida fuera. Hormigas y avispas pueden aparecer más rápido de lo que esperas.",
  "166. Lleva una pequeña libreta con códigos de barreras, campings y otra información importante. No todo está online.",
  "167. Antes de salir, haz siempre una “ronda” del coche. Comprueba que todo esté cerrado, desconectado y asegurado.",
  "168. Aprovecha los mercados y mercadillos locales. No solo más barato, sino también más sabroso.",
  "169. Recuerda la visera parasol para el parabrisas y el interior del coche no parecerá un horno.",
  "170. En lugares con insectos, usa repelentes naturales, por ejemplo, aceite de limón, lavanda o eucalipto.",
  "171. Mantén las herramientas en un solo lugar, fácilmente accesible. La caja de herramientas es tu amiga.",
  "172. Antes de instalarte para la noche, comprueba el nivel. A veces una pequeña pendiente puede convertir el sueño en una lucha por el equilibrio.",
  "173. No dejes dispositivos electrónicos a pleno sol. Se sobrecalientan fácilmente.",
  "174. Haz fotos de los documentos, la matrícula y el número VIN; pueden ser útiles en el extranjero.",
  "175. Recuerda cargar los powerbanks. En caso de no tener electricidad, aún podrás funcionar.",
  "176. Deja una nota con tu contacto en un lugar visible. Alguien puede intentar contactarte si hay un problema.",
  "177. En días calurosos, cocina por la mañana o por la tarde. Al mediodía es mejor descansar.",
  "178. En el viaje mantén una rutina. Estiramientos matutinos, café, 15 minutos de orden. Los pequeños rituales dan calma.",
  "179. Aprende comandos básicos para tu mascota. La seguridad ante todo.",
  "180. Intenta dormir con la cabeza más alta. Incluso un pequeño ángulo ayuda a respirar.",
  "181. Si algo funciona hoy, no significa que funcionará mañana, así que estate preparado para averías.",
  "182. Revisa siempre el estado de los frenos antes de una ruta larga por la montaña. Mejor con antelación que en el valle.",
  "183. Ábrete a conversaciones con los locales: es el mejor guía que encontrarás.",
  "184. Recuerda que cuantas menos cosas tienes, más fácil se vive. El minimalismo es un aliado del viaje.",
  "185. Lleva siempre pilas de repuesto o un cargador solar. La energía es la clave de la independencia.",
  "186. Si planeas acampar lejos de la civilización, deja a alguien información sobre tu ubicación.",
  "187. Asegura una señalización adecuada de la autocaravana por la noche. Los reflectantes pueden salvar vidas.",
  "188. Intenta repostar en regiones más baratas. Los precios del combustible pueden variar mucho.",
  "189. En lugares públicos intenta no llamar la atención. Un viajero que no atrae miradas es más seguro.",
  "190. Desinfecta las manos con frecuencia, especialmente después de repostar, usar baños públicos y hacer compras.",
  "191. Si duermes en un lugar con Wi-Fi, aprovecha para actualizar aplicaciones y descargar materiales para uso sin conexión.",
  "192. Haz una foto del lugar donde dejas el coche. Especialmente en ciudades grandes.",
  "193. En caso de avería, intenta mantener la calma. Cada situación tiene una solución.",
  "194. Comprueba cuáles son las fiestas locales y días libres. Puede afectar la disponibilidad de servicios.",
  "195. Evita conducir con el depósito en reserva. Ten siempre una reserva de seguridad.",
  "196. Asegura una ventilación adecuada al cocinar. Los vapores en un espacio pequeño pueden ser perjudiciales.",
  "197. Lleva contigo solo aplicaciones probadas. Menos es más cuando se trata de estabilidad.",
  "198. Si algo requiere reparación, arréglalo de inmediato. Posponerlo empeora la situación.",
  "199. Al elegir un lugar para dormir, presta atención a la inclinación del terreno; puede arruinar el sueño.",
  "200. Considera instalar detectores de gas, humo y monóxido de carbono, p. ej., Trigas. La seguridad es lo primero.",
  "201. Antes de salir del lugar de estacionamiento, haz una checklist rápida. Evitarás olvidar cosas importantes.",
  "202. Revisa el tiempo no solo para el día, sino también para los próximos días en esa región.",
  "203. Si cambias de país a menudo, considera comprar una tarjeta SIM internacional o una eSIM.",
  "204. Si aparcas en un lugar público, no dejes nada a la vista.",
  "205. Adapta tus hábitos alimenticios a la disponibilidad local de productos; eso facilita las compras.",
  "206. Si estás cansado, haz una parada. El cansancio al volante puede ser peligroso.",
  "207. Conviene tener una mesa y una silla plegables. Dan comodidad independientemente de las condiciones.",
  "208. Mantén el orden en los cables y cargadores.",
  "209. Anota los lugares donde lograste pasar la noche; pueden ser útiles en el futuro.",
  "210. Si tienes bicicleta o patinete, asegúralo con un buen candado.",
  "211. Encuentra tu propio ritmo de viaje. No copies el estilo de otros, porque cada viaje es distinto.",
  "212. No juzgues un lugar por la primera impresión; a veces vale la pena esperar a la mañana.",
  "213. Si planeas una parada más larga. Comprueba si cerca hay acceso a agua, baño y contenedores de basura.",
  "214. Comparte lugares solo con personas de confianza; no todos los sitios soportan mucha popularidad.",
  "215. Recuerda que a veces menos es más. No intentes verlo todo a la fuerza.",
  "216. Si tienes dificultad para dormir, prueba ruido blanco o aplicaciones de relajación.",
  "217. Guarda tus rutas; pueden convertirse en inspiración para otros (o para ti dentro de un año).",
  "218. Recuerda que no todas las averías son el fin del mundo; tómalo como parte de la aventura.",
  "219. Lleva siempre algo de comida “para una emergencia”. Preferiblemente de larga duración.",
  "220. Si usas una app de aparcamiento, deja una reseña y ayudarás a otros.",
  "221. Cambia el agua de los depósitos con frecuencia; evitarás mal olor o intoxicación.",
  "222. Aprende algunos ejercicios de estiramiento. El cuerpo en el viaje necesita movimiento.",
  "223. Usa bolsas de vacío para guardar la ropa; ahorrarás espacio.",
  "224. Si algo no cabe, significa que no era necesario.",
  "225. No olvides tu propia salud mental; permítete días perezosos.",
  "226. Asegura una luz para leer; las noches en la autocaravana son ideales para los libros.",
  "227. No dejes las llaves en el contacto, ni siquiera por un momento.",
  "228. Revisa siempre que tengas todos los cierres abrochados antes de arrancar.",
  "229. Aplica la regla: lo que no se ha usado durante 14 días se puede dejar o regalar.",
  "230. Si vas a un lugar nuevo, comprueba si hay cajeros automáticos y tiendas.",
  "231. Anota los nombres de las personas que conoces; eso construye relaciones.",
  "232. No dejes las fotos “para después”. Haz copias de seguridad regularmente.",
  "233. Lleva siempre una libreta, aunque sea pequeña, para anotaciones y observaciones rápidas o guarda tus reflexiones en el teléfono.",
  "234. Sujeta una llave de repuesto en algún escondite – algún día puede salvarte.",
  "235. Si alguien te ayudó desinteresadamente, anótalo y devuélveselo a otra persona.",
  "236. Prueba el equipo en condiciones extremas antes de salir, p. ej., bajas temperaturas.",
  "237. Es bueno tener cinta de doble cara, velcro y bridas que salvan el orden.",
  "238. Lleva en el teléfono un escaneo del permiso de conducir y del documento de identidad por si acaso.",
  "239. Si derramaste algo, límpialo de inmediato. Luego será más difícil.",
  "240. Haz a veces un “día offline”. Sin GPS, sin internet, solo tú y la carretera.",
  "241. No seas esclavo del plan; cambiar la ruta no es un fracaso.",
  "242. Si tienes una pasión, llévala contigo. Dibujo, juego, música. Lo que sea.",
  "243. En lugar de comprar recuerdos, recoge piedritas, conchas o dibuja los lugares que visitas.",
  "244. Date el derecho a descansar. No tienes que “tachar” todo.",
  "245. Recuerda que viajar también es responsabilidad. Eres un invitado.",
  "246. No uses luces demasiado brillantes por la noche. Respeta a los vecinos en el estacionamiento.",
  "247. Lleva siempre contigo algo dulce; puede mejorar el ánimo en momentos difíciles.",
  "248. Si te da miedo dormir en algún sitio, no duermas allí. Escucha siempre tu intuición y cambia de lugar.",
  "249. No compares tu viaje con el de otros. Cada camino es distinto y valioso.",
  "250. No olvides sonreír incluso en el peor día.",
  "251. Si te quedas a pasar la noche en la playa, asegúrate de no estar en la zona de marea.",
  "252. No te instales demasiado cerca de atracciones turísticas. Por la mañana puede haber multitudes.",
  "253. Intenta no dejar la autocaravana mucho tiempo sin vigilancia en lugares desconocidos.",
  "254. Si tienes un espacio pequeño, limpia a diario. El desorden crece rapidísimo.",
  "255. Al cocinar fuera, ten siempre a mano agua para apagar el fuego.",
  "256. Busca el equilibrio entre exploración y descanso.",
  "257. Comparte el espacio con respeto. No todos quieren hablar.",
  "258. Aparca siempre de modo que puedas salir fácilmente.",
  "259. Antes de abrir el toldo o desplegar la mesa, asegúrate de no bloquear el paso.",
  "260. Si no estás seguro del terreno, compruébalo a pie.",
  "261. No hagas ruido por la noche. Otros pueden estar descansando.",
  "262. Llévate una reserva de café o té. Las mañanas son importantes.",
  "263. Ten en el coche un lugar que sea “tu zona de calma”.",
  "264. Cuando llueve, no te quejes; adáptate. Puedes descansar o cambiar de lugar.",
  "265. Aprende reparaciones sencillas: desde pegar una ventana hasta cambiar un fusible.",
  "266. No dejes el equipo de camping sin vigilancia en lugares concurridos.",
  "267. Si puedes, ayuda a otros vanlifers.",
  "268. Reúne inspiraciones y anota lo que funcionó en otros.",
  "269. A veces vale la pena pagar por un lugar para dormir por seguridad o comodidad.",
  "270. No subestimes los avisos meteorológicos. Pueden salvar el día o la noche.",
  "271. Aprovecha bibliotecas o cafeterías: son buenos lugares para Wi-Fi y descanso.",
  "272. Ten en el maletero un conjunto de ropa “para cualquier tiempo”.",
  "273. Conviene llevar algo de efectivo en la moneda local – no en todas partes funciona la tarjeta.",
  "274. Si haces compras, apoya a los negocios locales.",
  "275. Incluso una parada de un día merece buena organización.",
  "276. Acordad con tu pareja un “tiempo offline” para cada uno.",
  "277. Silencia el teléfono al menos una vez al día por salud mental.",
  "278. Si puedes, cuida el verde a tu alrededor: riega un arbolito, limpia, planta algo.",
  "279. Recuerda que menos es más. No sobrecargues el coche.",
  "280. Si no puedes dormir, sal a dar un paseo corto; ayuda.",
  "281. Revisa las normas locales de aparcamiento. Pueden variar incluso entre ciudades.",
  "282. Haz a veces un día sin conducir. La regeneración es igual de importante.",
  "283. Si alguien te invita a comer. Lleva algo a cambio.",
  "284. Usa apps del tiempo, pero ten tus propios ojos. Las nubes dicen mucho.",
  "285. Si ves que a alguien le cuesta más, pregunta si no necesita ayuda o hablar.",
  "286. Antes de una ruta larga, revisa siempre la presión de los neumáticos.",
  "287. Antes de ponerte en marcha, asegúrate de que los armarios y ventanas estén cerrados, el gas cerrado, el escalón recogido y todos los objetos sueltos asegurados.",
  "288. Anota los sabores locales en una libreta. El sabor también es un recuerdo.",
  "289. Limpia los paneles solares – una superficie sucia es menos energía.",
  "290. Guarda bolsas de basura en varios lugares. Siempre vienen bien.",
  "291. Si viajas con niños, introduce rituales y normas que les den sensación de seguridad.",
  "292. Después de cada repostaje, revisa también los líquidos (refrigerante, limpiaparabrisas, aceite).",
  "293. No dejes papel higiénico en la naturaleza, ni siquiera el biodegradable.",
  "294. Encuentra tiempo para hablar con los locales: es la mejor fuente de conocimiento sobre la zona.",
  "295. No seas insistente. No todos quieren formar parte de la comunidad vanlife.",
  "296. Haz una lista de cosas que no llevarás la próxima vez. Aprende de la experiencia.",
  "297. Recuerda que menos planes = más aventuras.",
  "298. A veces que todo funcione… pero no hagas nada.",
  "299. Sigue las fases de la luna. Una noche con luna llena puede ser mágica.",
  "300. ¡No lo olvides! Los mejores recuerdos se crean en los momentos más simples.",
  "301. Instala alfombrillas antideslizantes en la entrada de la autocaravana para evitar lesiones.",
  "302. Crea una copia digital y otra en papel de documentos importantes (DNI, pasaporte) y guárdalas en lugares separados.",
  "303. Guarda el botiquín en dos lugares. En la cabina y en un lugar accesible desde fuera.",
  "304. Marca cables y conductores con cintas de colores para encontrarlos rápido en caso de avería.",
  "305. Instala en la puerta un sensor de vapores de gas.",
  "306. Coloca un imán con un juego de llaves de repuesto bajo el vehículo en una caja metálica resistente a las condiciones.",
  "307. Comprueba la resistencia de las conexiones de agua a bajas temperaturas para evitar roturas en invierno.",
  "308. Invierte en un generador portátil de sonido (ruido blanco) para noches ruidosas.",
  "309. Marca en el mapa de la app GPS las fuentes de ayuda médica de emergencia.",
  "310. Usa aplicaciones para monitorear el clima satelital.",
  "311. Guarda en la nevera de la autocaravana acumuladores de hielo para mantener baja la temperatura por más tiempo.",
  "312. Lleva en la cartera una mini brújula de emergencia.",
  "313. Limpia regularmente los filtros de aire y ventiladores para evitar que la instalación se obstruya.",
  "314. Haz fotos del interior de la autocaravana antes de salir para tener prueba del estado en caso de daño.",
  "315. Reduce el nivel de agua gris y negra siempre antes de una ruta larga. Más masa = más consumo.",
  "316. Adjunta el manual de cada dispositivo en forma de código QR.",
  "317. Guarda un juego adicional de herramientas en un lugar accesible desde fuera del vehículo.",
  "318. Prueba el funcionamiento del aire acondicionado y la calefacción durante una parada antes de salir.",
  "319. Abastécete de tubos termorretráctiles y cinta aislante para reparaciones rápidas.",
  "320. Abastécete de bombillas de repuesto para la iluminación de la autocaravana.",
  "321. Instala un módulo Bluetooth para el control remoto de la iluminación y la calefacción.",
  "322. Coloca materiales reflectantes en puntos exteriores del coche.",
  "323. Registra el nivel de combustible y los recorridos en una aplicación dedicada.",
  "324. Usa bolsas de vacío para la ropa para ahorrar espacio.",
  "325. Invierte en un dispositivo portátil para medir la calidad del aire.",
  "326. Abastécete de una cafetera portátil para cápsulas o filtros de goteo.",
  "327. Protege el teléfono con una funda impermeable por si llueve.",
  "328. Usa accesorios de cocina de madera para reducir residuos plásticos.",
  "329. Monta un filtro de agua carbon block en el grifo de la autocaravana.",
  "330. Establece un procedimiento de alarma en caso de fuga de gas.",
  "331. Comprueba regularmente la estanqueidad de las juntas en puertas y ventanas.",
  "332. Prepara una linterna de emergencia con posibilidad de carga por manivela.",
  "333. Lleva contigo un mini powerbank solar.",
  "334. Los conectores Wago son una gran solución para unir cables dañados.",
  "335. Instala una app para identificar plantas y animales en el terreno.",
  "336. Usa aislantes térmicos en las ventanas para noches más frías.",
  "337. Invierte en un alargador de red con protección contra sobretensiones.",
  "338. Lleva contigo un mini botiquín para quemaduras y pequeños cortes.",
  "339. Guarda bolsas biodegradables para residuos orgánicos.",
  "340. Instala un filtro HEPA para purificar el aire dentro del vehículo.",
  "341. Prueba el módulo de calefacción de gas a temperaturas bajo cero.",
  "342. Crea un calendario de revisiones y guarda las fechas en el calendario.",
  "343. Usa cucharas y espátulas de madera al cocinar en la hoguera.",
  "344. Protege los cables USB en un estuche rígido para evitar daños.",
  "345. Anota un recordatorio de la revisión técnica de tu vehículo.",
  "346. Abastécete de un mini kit para reparar electrónica (soldador, cintas, cablecitos).",
  "347. Lleva un registro de servicio en una app móvil o en una libreta.",
  "348. Ordena cables y mangueras para que no se enreden durante la conducción.",
  "349. Lleva una mascarilla antipolvo para caminos sin asfaltar, para proteger las vías respiratorias.",
  "350. Disfruta cada momento del viaje, pero mantén siempre la sensatez y la prioridad en la seguridad.",
]
