// Created by Mateusz Mlynarski
// All rights reserved

import Foundation

let rulesListPL: [String] = [
  "1. Zainwestuj w dobry materac. Sen jest bardzo ważny dla Twojego zdrowia i samopoczucia.",
  "2. Warto mieć w aucie podstawową walizkę z narzędziami – nawet jeśli sam nie potrafisz naprawić samochodu, ktoś może Ci pomóc.",
  "3. Przygotuj listę rzeczy, które musisz zabrać ze sobą przed każdym wyjazdem.",
  "4. Zawsze miej przy sobie zestaw pierwszej pomocy.",
  "5. Planuj swoje wyjazdy z wyprzedzeniem i zwracaj uwagę na warunki atmosferyczne.",
  "6. Naucz się korzystać z różnych źródeł energii – od paneli słonecznych po generator.",
  "7. Zawsze miej przy sobie wystarczającą ilość wody pitnej.",
  "8. Przetestuj wszystkie urządzenia w kamperze lub przyczepie przed wyjazdem.",
  "9. Naucz się, jak działa system odprowadzania ścieków w Twoim kamperze lub przyczepie.",
  "10. Zawsze zamykaj drzwi i okna, kiedy opuszczasz kampera lub przyczepę.",
  "11. Pamiętaj o regularnym serwisowaniu i przeglądach kampera lub przyczepy.",
  "12. Zaopatrz się w niezbędne leki, takie jak środki przeciwbólowe czy węgiel aktywny.",
  "13. Przed wyjazdem sprawdź stan techniczny swojego pojazdu.",
  "14. Jeśli wyjeżdżasz w ziemię, nawet gdy na miejscu jest lato, jedź na zimowych oponach.",
  "15. Zawsze miej w samochodzie butelkę oleju silnikowego dedykowanego Twojemu pojazdowi.",
  "16. Trudna droga dojazdowa zazwyczaj kryje na końcu wspaniałą, dziką miejscówkę.",
  "17. Dbaj o innych – jeśli parkujesz między kamperami, zachowaj odpowiedni odstęp.",
  "18. Jeśli wychodzisz późnym popołudniem na spacer, zabierz ze sobą latarkę lub powerbank z kablem do telefonu.",
  "19. Jeśli pomylisz drogę, nie zawracaj – daj się ponieść przygodzie, ale oczywiście z rozwagą.",
  "20. Jeśli wjeżdżasz pod górę na drugim biegu, zjeżdżaj z góry również na drugim biegu.",
  "21. Jeśli podróżujesz sam, często udostępniaj najbliższej rodzinie swoją lokalizację.",
  "22. Jeśli masz możliwość uzupełnienia wody i wylania wody szarej lub czarnej, zrób to – może się okazać, że najbliższy serwis będzie nie po drodze.",
  "23. Jeśli podróżujesz z drugą osobą, zawsze ustalcie sposób komunikacji na wypadek zgubienia się lub rozdzielenia.",
  "24. Jeśli w pobliżu nie ma kosza, zabieraj śmieci ze sobą.",
  "25. Długi wąż do zatankowania wody jest zawsze lepszy niż krótki.",
  "26. Warto zaopatrzyć się w różne końcówki nakręcane na zawory wody – nigdy nie wiesz, co zastaniesz na miejscu.",
  "27. Czy droga do miejsca, w którym zamierzasz spać, prowadzi z górki? Sprawdź prognozę pogody – jeśli zapowiada się deszcz, wybierz inne miejsce, bo rano możesz mieć problem z wyjazdem.",
  "28. Nigdy się nie zatrzymuj, gdy ktoś do Ciebie macha – zarówno na zwykłej drodze, jak i na autostradzie.",
  "29. Oszczędzaj wodę, gaz i prąd.",
  "30. Pakując się na długi wyjazd, nie zabieraj zbędnych rzeczy – z czasem przekonasz się, że wcale ich nie potrzebujesz.",
  "31. Jeśli znalazłeś świetne miejsce w Google Maps lub Park4Night, sprawdź, czy w pobliżu znajdują się inne ciekawe atrakcje – może się okazać, że to miejsce wkrótce przestanie być dostępne.",
  "32. Jeśli dotarłeś na miejsce i nie czujesz się tam bezpiecznie, zmień lokalizację.",
  "33. Jeśli nie czujesz się bezpiecznie w miejscu, w którym jesteś, poszukaj innych kamperów – w grupie będzie bezpieczniej.",
  "34. Znajdź w aucie miejsce na cenne rzeczy – możesz zainstalować mały sejf lub metalową, zamykaną skrzynkę. Pamiętaj, aby odpowiednio zabezpieczyć je przed kradzieżą.",
  "35. Dbaj o środowisko, w którym podróżujesz – przestrzegaj zasad ekologicznych, takich jak utrzymanie miejsca w czystości i segregacja śmieci.",
  "36. Ciesz się wolnością i przygodą, jaką oferuje van life. Niech podróż stanie się dla Ciebie niezapomnianym doświadczeniem, które pozostanie w Twojej pamięci na zawsze. Żyj tą chwilą!",
  "37. Pamiętaj o poszanowaniu lokalnych kultur i tradycji.",
  "38. Przestrzegaj przepisów drogowych w kraju, przez który podróżujesz, aby uniknąć mandatu.",
  "39. Ogranicz korzystanie z plastikowych jednorazowych przedmiotów, takich jak kubki czy sztućce.",
  "40. Podczas długiej podróży rób krótkie przystanki na rozprostowanie – możesz również zmieniać pozycję fotela, co przyniesie ulgę Twojemu kręgosłupowi.",
  "41. Bądź elastyczny i otwarty na zmiany planów, ponieważ w podróży zawsze może pojawić się coś nieprzewidywalnego.",
  "42. Przygotuj się na brak zasięgu telefonu lub internetu w niektórych miejscach.",
  "43. Pamiętaj, aby wypocząć i zrelaksować się, a nie tylko podróżować non-stop.",
  "44. Przed podróżą do danego kraju pobierz mapy offline – zarówno kraju docelowego, jak i tras przejazdu.",
  "45. Zainstaluj odpowiednie aplikacje do znajdowania miejsc do spania (Google Maps, Park4Night itp.).",
  "46. Zawsze miej przy sobie wystarczającą ilość gotówki lub karty płatnicze, aby móc pokryć koszty podróży.",
  "47. Większą sumę gotówki podziel na kilka mniejszych i rozdziel je w nieoczywistych miejscach – schowek samochodowy to pierwsze miejsce, które sprawdzi potencjalny złodziej.",
  "48. Daj dobry przykład – jeśli widzisz śmieci pozostawione przez innych, zbierz je i wyrzuć w odpowiednim miejscu.",
  "49. Wykup ubezpieczenie podróżne, assistance oraz holowanie.",
  "50. Dbaj o swoje bezpieczeństwo oraz bezpieczeństwo swoich bliskich.",
  "51. Korzystaj z możliwości spotkania nowych ludzi i poznawania różnych kultur.",
  "52. Bądź gotowy na nieprzewidziane wydatki, takie jak naprawa samochodu lub zakup dodatkowego paliwa.",
  "53. W przypadku braku pomysłu na miejsce noclegu, zapytaj o możliwość postoju – na przykład na stacji benzynowej.",
  "54. Przygotuj się na różne warunki drogowe, takie jak kamieniste drogi, wysokie góry czy trasy z ostrymi zakrętami.",
  "55. Przestrzegaj zasad wjazdu do parków narodowych lub innych obszarów chronionych, aby nie narażać przyrody na szkody, a siebie na dodatkowe wydatki.",
  "56. Bądź cierpliwy – podczas jazdy samochodem możesz napotkać trudne drogi, natłok ludzi lub problemy techniczne, które mogą opóźnić podróż.",
  "57. Pamiątki – pamiętaj, by zostawić trochę miejsca na rzeczy zakupione w podróży.",
  "58. Odkrywaj nie tylko nowe miejsca, ale także próbuj lokalnej kuchni. Otwórz się na nowe smaki – być może z podróży wrócisz z nowym ulubionym daniem.",
  "59. Przestrzegaj zasad kempingowych – pozostaw miejsce takim, jakim je zastaliśmy, oraz przestrzegaj zasad dotyczących ognisk i grillowania.",
  "60. Unikaj zanieczyszczania środowiska – stosuj ekologiczne kosmetyki i środki czystości.",
  "61. Możesz zminimalizować zużycie wody, korzystając z publicznych źródeł, w tym toalet i pryszniców.",
  "62. Spróbuj nauczyć się nowych umiejętności, takich jak gotowanie na ognisku, wspinaczka czy surfowanie, aby poszerzyć swoje horyzonty i czerpać więcej radości z podróży.",
  "63. Małe miasteczka lub wioski w okolicy, w której przebywasz, mogą być atrakcyjniejsze niż zatłoczone turystyczne miasta.",
  "64. Warto zawsze mieć w aucie podstawowe produkty spożywcze, takie jak mąka, drożdże, cukier czy sól.",
  "65. Ucz się na błędach i nie przestawaj eksperymentować z różnymi rozwiązaniami.",
  "66. Pamiętaj o wykorzystywaniu czasu wolnego do rozwoju swoich zainteresowań i pasji – czytaj, ucz się języków obcych lub twórz sztukę.",
  "67. Ciesz się naturą i pozwól sobie na chwile refleksji oraz medytacji, aby zyskać nowe perspektywy na swoje życie i cele.",
  "68. Bądź gotowy na niespodziewane wyzwania i sytuacje – nie zawsze będzie łatwo.",
  "69. Jeśli podróżujesz sam/sama, pozostań trzeźwy – nie wiesz, czy policja nie przyjedzie i nie nakaże zmienić miejsca postoju.",
  "70. Nie wchodź w dyskusje z lokalną policją ani z mieszkańcami – okaż im szacunek.",
  "71. Bądź wdzięczny za każdą chwilę i doświadczenie, które napotkasz na swojej drodze, oraz za każdą osobę, która podzieli się z Tobą swoją historią i mądrością.",
  "72. Pamiętaj, że podróżowanie samochodem wiąże się z pewnym ryzykiem – zawsze bądź czujny i ostrożny na drodze.",
  "73. Dbaj o relacje z rodziną i przyjaciółmi, utrzymując z nimi kontakt i dzieląc się swoimi doświadczeniami.",
  "74. Bądź otwarty na naukę i rozwój osobisty – wykorzystuj czas spędzony w samochodzie na słuchanie audiobooków, podcastów lub naukę nowych umiejętności.",
  "75. Uważaj na kieszonkowców w komunikacji miejskiej – miej zawsze oko na swój bagaż.",
  "76. Jeśli podróżujesz ze zwierzakiem, zadbaj o to, by miał odpowiednią temperaturę oraz dostęp do wody pitnej.",
  "77. Zamień chemiczne środki do toalety na ekologiczne – na przykład saszetki lub tabletki do szamb.",
  "78. Nie zostawiaj na noc sprzętu turystycznego (krzesełka, stolika, grilla) na zewnątrz.",
  "79. Bądź pokorny/a wobec miejscowych i przechodniów – uśmiechnij się, bo jesteś częścią ich codziennej rutyny i otoczenia.",
  "80. Bądź życzliwy/a dla miejscowych – może się zdarzyć, że będziesz potrzebować ich pomocy w niespodziewanej sytuacji.",
  "81. Dron to doskonałe narzędzie do tworzenia pamiątek z podróży. Pamiętaj, aby zachować bezpieczeństwo i prywatność innych osób.",
  "82. Jeśli masz drona, sprawdź obowiązujące przepisy w kraju, w którym się znajdujesz, i przestrzegaj zakazów lotu w wydzielonych strefach.",
  "83. Jeśli masz drona, nigdy nie startuj w pobliżu lotniska.",
  "84. Nie zasłaniaj autem widoku z domu, restauracji czy tarasu.",
  "85. Jeśli Twój van lub samochód kempingowy zajmuje więcej niż jedno miejsce parkingowe, zaparkuj go w innym miejscu.",
  "86. Czytaj lub tłumacz informacje na znakach.",
  "87. Czasami znalezienie miejsca parkingowego może być problemem – zapytaj miejscowych lub policję o wskazanie dogodnego miejsca na nocleg.",
  "88. Zacznij pisać dziennik z podróży – może to być świetna pamiątka.",
  "89. Zabierz ze sobą grę planszową lub karty – urozmaicą one czas podczas złej pogody.",
  "90. Zaplanuj zakupy, tankowanie wody oraz opróżnienie toalety i szarej wody dzień wcześniej.",
  "91. Weź pod uwagę, że gotowanie w kamperze lub campervanie zajmuje znacznie więcej czasu niż w mieszkaniu.",
  "92. Przygotuj się na częste sprzątanie auta – zaopatrz się w zmiotkę lub odkurzacz.",
  "93. Przygotuj się na obecność licznych owadów – nie tylko komarów. Moskitiera może być jedynie częściowym rozwiązaniem.",
  "94. Nie zapalaj wieczorem światła przy uchylonych drzwiach.",
  "95. Przed wyjazdem sprawdź stan koła zapasowego oraz zaopatrz się w zestaw do naprawy opony – pozwoli Ci to dojechać do najbliższej wulkanizacji.",
  "96. Bądź gotowy wyjść ze swojej strefy komfortu.",
  "97. Jeśli pracujesz zdalnie, zadbaj o wygodne miejsce do pracy – leżak i plaża wyglądają dobrze tylko na zdjęciach.",
  "98. Każdy dzień to przygoda – traktuj ją jako dobrą zabawę.",
  "99. Jeśli podróżujesz ze zwierzakiem, trzymaj go blisko auta.",
  "100. Gdy w telefonie braknie zasięgu, warto mieć przy sobie papierową mapę.",
  "101. Warunki pogodowe podczas spaceru mogą się nagle zmienić. Warto mieć przy sobie płaszcz przeciwdeszczowy, który zmieścisz w kieszeni.",
  "102. Przed podróżą sprawdź ważność paszportu oraz innych dokumentów.",
  "103. Wyrób Europejską Kartę Ubezpieczenia Zdrowotnego (EKUZ).",
  "104. Zaopatrz się w mały czajnik do zagotowania wody na kawę – zaoszczędzisz czas i wodę.",
  "105. Pamiętaj o kremie z filtrem UV – latem, zimą, a nawet podczas wędrówek w góry.",
  "106. Rób listę zakupów – unikniesz w ten sposób niepotrzebnych lub dodatkowych wydatków.",
  "107. Nie pakuj się na ostatnią chwilę – przygotuj potrzebne rzeczy przynajmniej dwa dni wcześniej.",
  "108. Butelka alkoholu lub inny prezent to dobry pomysł, by podziękować za pomoc.",
  "109. Jeśli jesteś blisko stacji paliw i świeci się rezerwa, zatankuj – kolejna stacja może być za daleko.",
  "110. Dziel się swoimi doświadczeniami z innymi.",
  "111. Gdy nadarzy się okazja do zatankowania wody lub opróżnienia toalety, zrób to – podobnie jak przy tankowaniu paliwa, nigdy nie wiesz, kiedy pojawi się kolejna szansa.",
  "112. Jeśli podróżujesz z kimś, szczególnie w krajach spoza UE, warto ustalić sposób komunikacji w sytuacji braku internetu.",
  "113. Jeśli masz złe przeczucia odnośnie stanu swojego pojazdu, nie ignoruj ich.",
  "114. Przy naprawie samochodu zaczynaj od najdroższych elementów. Jeśli planujesz naprawy w tańszym kraju, pamiętaj, że może Cię to kosztować dwa razy więcej.",
  "115. Jeśli masz złe przeczucia co do miejsca, w którym zamierzasz nocować, poszukaj innego – nie kusić losu.",
  "116. Nie odkładaj śniadania na później – w ciągu dnia wiele się dzieje, a pierwszy posiłek, o 19:00, zwykle nazywany jest kolacją.",
  "117. Jeśli czas nie pokrywa się z przebytą liczbą kilometrów, rozważ zmianę miejscówki – może to oznaczać, że droga jest bardzo słabej jakości lub off-road.",
  "118. Jeśli Google Maps źle wskazuje drogę, warto sprawdzić ją w innej aplikacji.",
  "119. Jeśli coś się zepsuło, a następnie samo się naprawiło, to oznacza, że nadal jest uszkodzone.",
  "120. Teytytki, szara taśma i WD-40 – miej je zawsze pod ręką.",
  "121. Jeśli wczorajsza impreza się przedłużyła, odczekaj, zanim wsiądziesz za kierownicę, lub udaj się na komisariat policji i poproś o badanie alkomatem.",
  "122. Jeśli jesteś w górach i spadł śnieg, poczekaj, aż pojawi się pług śnieżny. Jedź za nim – to znacznie ułatwi drogę.",
  "123. Jeżeli gdzieś wyjeżdżasz, zawsze zabierz ze sobą paszport – nigdy nie wiesz, gdzie przygoda Cię poniesie.",
  "124. Zapoznaj się z zasadami ruchu drogowego oraz kulturą jazdy tamtejszych kierowców.",
  "125. Sprawdź, jakie jest obowiązkowe wyposażenie samochodu w kraju, do którego jedziesz, oraz przez które przejeżdżasz (np. kamizelki, gaśnica, trójkąt).",
  "126. Pamiętaj o zabraniu Zielonej Karty, gdy wyjeżdżasz autem za granicę.",
  "127. Jeśli to możliwe, wykup dodatkowe ubezpieczenie obowiązujące w kraju, do którego jedziesz.",
  "128. Jeśli planujesz wyjazd poza Unię Europejską, sprawdź wymagania obowiązujące w danym kraju.",
  "129. Sprawdź, czy w kraju, do którego jedziesz, wymagane są szczepienia.",
  "130. Zapytaj lokalnych mieszkańców o atrakcje w okolicy.",
  "131. Zapoznaj się z kulturą danego kraju, np. z lokalnymi gestami.",
  "132. Zawsze zapinaj pasy bezpieczeństwa – mogą uratować Ci życie.",
  "133. Unikaj prowadzenia pojazdu po spożyciu alkoholu, nawet po jednym piwie."
]
