// Created by Mateusz Mlynarski
// All rights reserved

import Foundation

let rulesListPL: [String] = [
  "1. Zainwestuj w dobry materac. Sen jest bardzo ważny dla Twojego zdrowia i samopoczucia.",
  "2. Warto mieć w aucie podstawową walizkę z narzędziami – nawet jeśli sam nie potrafisz naprawić samochodu, ktoś może Ci pomóc.",
  "3. Przygotuj listę rzeczy, które musisz zabrać ze sobą przed każdym wyjazdem.",
  "4. Zawsze miej przy sobie zestaw pierwszej pomocy.",
  "5. Planuj swoje wyjazdy z wyprzedzeniem i zwracaj uwagę na warunki atmosferyczne.",
  "6. Naucz się korzystać z różnych źródeł energii – od paneli słonecznych po generator.",
  "7. Zawsze miej przy sobie wystarczającą ilość wody pitnej.",
  "8. Przetestuj wszystkie urządzenia w kamperze lub przyczepie przed wyjazdem.",
  "9. Naucz się, jak działa system odprowadzania ścieków w Twoim kamperze lub przyczepie.",
  "10. Zawsze zamykaj drzwi i okna, kiedy opuszczasz kampera lub przyczepę.",
  "11. Pamiętaj o regularnym serwisowaniu i przeglądach kampera lub przyczepy.",
  "12. Zaopatrz się w niezbędne leki, takie jak środki przeciwbólowe czy węgiel aktywny.",
  "13. Przed wyjazdem sprawdź stan techniczny swojego pojazdu.",
  "14. Jeśli wyjeżdżasz w ziemię, nawet gdy na miejscu jest lato, jedź na zimowych oponach.",
  "15. Zawsze miej w samochodzie butelkę oleju silnikowego dedykowanego Twojemu pojazdowi.",
  "16. Trudna droga dojazdowa zazwyczaj kryje na końcu wspaniałą, dziką miejscówkę.",
  "17. Dbaj o innych – jeśli parkujesz między kamperami, zachowaj odpowiedni odstęp.",
  "18. Jeśli wychodzisz późnym popołudniem na spacer, zabierz ze sobą latarkę lub powerbank z kablem do telefonu.",
  "19. Jeśli pomylisz drogę, nie zawracaj – daj się ponieść przygodzie, ale oczywiście z rozwagą.",
  "20. Jeśli wjeżdżasz pod górę na drugim biegu, zjeżdżaj z góry również na drugim biegu.",
  "21. Jeśli podróżujesz sam, często udostępniaj najbliższej rodzinie swoją lokalizację.",
  "22. Jeśli masz możliwość uzupełnienia wody i wylania wody szarej lub czarnej, zrób to – może się okazać, że najbliższy serwis będzie nie po drodze.",
  "23. Jeśli podróżujesz z drugą osobą, zawsze ustalcie sposób komunikacji na wypadek zgubienia się lub rozdzielenia.",
  "24. Jeśli w pobliżu nie ma kosza, zabieraj śmieci ze sobą.",
  "25. Długi wąż do zatankowania wody jest zawsze lepszy niż krótki.",
  "26. Warto zaopatrzyć się w różne końcówki nakręcane na zawory wody – nigdy nie wiesz, co zastaniesz na miejscu.",
  "27. Czy droga do miejsca, w którym zamierzasz spać, prowadzi z górki? Sprawdź prognozę pogody – jeśli zapowiada się deszcz, wybierz inne miejsce, bo rano możesz mieć problem z wyjazdem.",
  "28. Nigdy się nie zatrzymuj, gdy ktoś do Ciebie macha – zarówno na zwykłej drodze, jak i na autostradzie.",
  "29. Oszczędzaj wodę, gaz i prąd.",
  "30. Pakując się na długi wyjazd, nie zabieraj zbędnych rzeczy – z czasem przekonasz się, że wcale ich nie potrzebujesz.",
  "31. Jeśli znalazłeś świetne miejsce w Google Maps lub Park4Night, sprawdź, czy w pobliżu znajdują się inne ciekawe atrakcje – może się okazać, że to miejsce wkrótce przestanie być dostępne.",
  "32. Jeśli dotarłeś na miejsce i nie czujesz się tam bezpiecznie, zmień lokalizację.",
  "33. Jeśli nie czujesz się bezpiecznie w miejscu, w którym jesteś, poszukaj innych kamperów – w grupie będzie bezpieczniej.",
  "34. Znajdź w aucie miejsce na cenne rzeczy – możesz zainstalować mały sejf lub metalową, zamykaną skrzynkę. Pamiętaj, aby odpowiednio zabezpieczyć je przed kradzieżą.",
  "35. Dbaj o środowisko, w którym podróżujesz – przestrzegaj zasad ekologicznych, takich jak utrzymanie miejsca w czystości i segregacja śmieci.",
  "36. Ciesz się wolnością i przygodą, jaką oferuje van life. Niech podróż stanie się dla Ciebie niezapomnianym doświadczeniem, które pozostanie w Twojej pamięci na zawsze. Żyj tą chwilą!",
  "37. Pamiętaj o poszanowaniu lokalnych kultur i tradycji.",
  "38. Przestrzegaj przepisów drogowych w kraju, przez który podróżujesz, aby uniknąć mandatu.",
  "39. Ogranicz korzystanie z plastikowych jednorazowych przedmiotów, takich jak kubki czy sztućce.",
  "40. Podczas długiej podróży rób krótkie przystanki na rozprostowanie – możesz również zmieniać pozycję fotela, co przyniesie ulgę Twojemu kręgosłupowi.",
  "41. Bądź elastyczny i otwarty na zmiany planów, ponieważ w podróży zawsze może pojawić się coś nieprzewidywalnego.",
  "42. Przygotuj się na brak zasięgu telefonu lub internetu w niektórych miejscach.",
  "43. Pamiętaj, aby wypocząć i zrelaksować się, a nie tylko podróżować non-stop.",
  "44. Przed podróżą do danego kraju pobierz mapy offline – zarówno kraju docelowego, jak i tras przejazdu.",
  "45. Zainstaluj odpowiednie aplikacje do znajdowania miejsc do spania (Google Maps, Park4Night itp.).",
  "46. Zawsze miej przy sobie wystarczającą ilość gotówki lub karty płatnicze, aby móc pokryć koszty podróży.",
  "47. Większą sumę gotówki podziel na kilka mniejszych i rozdziel je w nieoczywistych miejscach – schowek samochodowy to pierwsze miejsce, które sprawdzi potencjalny złodziej.",
  "48. Daj dobry przykład – jeśli widzisz śmieci pozostawione przez innych, zbierz je i wyrzuć w odpowiednim miejscu.",
  "49. Wykup ubezpieczenie podróżne, assistance oraz holowanie.",
  "50. Dbaj o swoje bezpieczeństwo oraz bezpieczeństwo swoich bliskich.",
  "51. Korzystaj z możliwości spotkania nowych ludzi i poznawania różnych kultur.",
  "52. Bądź gotowy na nieprzewidziane wydatki, takie jak naprawa samochodu lub zakup dodatkowego paliwa.",
  "53. W przypadku braku pomysłu na miejsce noclegu, zapytaj o możliwość postoju – na przykład na stacji benzynowej.",
  "54. Przygotuj się na różne warunki drogowe, takie jak kamieniste drogi, wysokie góry czy trasy z ostrymi zakrętami.",
  "55. Przestrzegaj zasad wjazdu do parków narodowych lub innych obszarów chronionych, aby nie narażać przyrody na szkody, a siebie na dodatkowe wydatki.",
  "56. Bądź cierpliwy – podczas jazdy samochodem możesz napotkać trudne drogi, natłok ludzi lub problemy techniczne, które mogą opóźnić podróż.",
  "57. Pamiątki – pamiętaj, by zostawić trochę miejsca na rzeczy zakupione w podróży.",
  "58. Odkrywaj nie tylko nowe miejsca, ale także próbuj lokalnej kuchni. Otwórz się na nowe smaki – być może z podróży wrócisz z nowym ulubionym daniem.",
  "59. Przestrzegaj zasad kempingowych – pozostaw miejsce takim, jakim je zastaliśmy, oraz przestrzegaj zasad dotyczących ognisk i grillowania.",
  "60. Unikaj zanieczyszczania środowiska – stosuj ekologiczne kosmetyki i środki czystości.",
  "61. Możesz zminimalizować zużycie wody, korzystając z publicznych źródeł, w tym toalet i pryszniców.",
  "62. Spróbuj nauczyć się nowych umiejętności, takich jak gotowanie na ognisku, wspinaczka czy surfowanie, aby poszerzyć swoje horyzonty i czerpać więcej radości z podróży.",
  "63. Małe miasteczka lub wioski w okolicy, w której przebywasz, mogą być atrakcyjniejsze niż zatłoczone turystyczne miasta.",
  "64. Warto zawsze mieć w aucie podstawowe produkty spożywcze, takie jak mąka, drożdże, cukier czy sól.",
  "65. Ucz się na błędach i nie przestawaj eksperymentować z różnymi rozwiązaniami.",
  "66. Pamiętaj o wykorzystywaniu czasu wolnego do rozwoju swoich zainteresowań i pasji – czytaj, ucz się języków obcych lub twórz sztukę.",
  "67. Ciesz się naturą i pozwól sobie na chwile refleksji oraz medytacji, aby zyskać nowe perspektywy na swoje życie i cele.",
  "68. Bądź gotowy na niespodziewane wyzwania i sytuacje – nie zawsze będzie łatwo.",
  "69. Jeśli podróżujesz sam/sama, pozostań trzeźwy – nie wiesz, czy policja nie przyjedzie i nie nakaże zmienić miejsca postoju.",
  "70. Nie wchodź w dyskusje z lokalną policją ani z mieszkańcami – okaż im szacunek.",
  "71. Bądź wdzięczny za każdą chwilę i doświadczenie, które napotkasz na swojej drodze, oraz za każdą osobę, która podzieli się z Tobą swoją historią i mądrością.",
  "72. Pamiętaj, że podróżowanie samochodem wiąże się z pewnym ryzykiem – zawsze bądź czujny i ostrożny na drodze.",
  "73. Dbaj o relacje z rodziną i przyjaciółmi, utrzymując z nimi kontakt i dzieląc się swoimi doświadczeniami.",
  "74. Bądź otwarty na naukę i rozwój osobisty – wykorzystuj czas spędzony w samochodzie na słuchanie audiobooków, podcastów lub naukę nowych umiejętności.",
  "75. Uważaj na kieszonkowców w komunikacji miejskiej – miej zawsze oko na swój bagaż.",
  "76. Jeśli podróżujesz ze zwierzakiem, zadbaj o to, by miał odpowiednią temperaturę oraz dostęp do wody pitnej.",
  "77. Zamień chemiczne środki do toalety na ekologiczne – na przykład saszetki lub tabletki do szamb.",
  "78. Nie zostawiaj na noc sprzętu turystycznego (krzesełka, stolika, grilla) na zewnątrz.",
  "79. Bądź pokorny/a wobec miejscowych i przechodniów – uśmiechnij się, bo jesteś częścią ich codziennej rutyny i otoczenia.",
  "80. Bądź życzliwy/a dla miejscowych – może się zdarzyć, że będziesz potrzebować ich pomocy w niespodziewanej sytuacji.",
  "81. Dron to doskonałe narzędzie do tworzenia pamiątek z podróży. Pamiętaj, aby zachować bezpieczeństwo i prywatność innych osób.",
  "82. Jeśli masz drona, sprawdź obowiązujące przepisy w kraju, w którym się znajdujesz, i przestrzegaj zakazów lotu w wydzielonych strefach.",
  "83. Jeśli masz drona, nigdy nie startuj w pobliżu lotniska.",
  "84. Nie zasłaniaj autem widoku z domu, restauracji czy tarasu.",
  "85. Jeśli Twój van lub samochód kempingowy zajmuje więcej niż jedno miejsce parkingowe, zaparkuj go w innym miejscu.",
  "86. Czytaj lub tłumacz informacje na znakach.",
  "87. Czasami znalezienie miejsca parkingowego może być problemem – zapytaj miejscowych lub policję o wskazanie dogodnego miejsca na nocleg.",
  "88. Zacznij pisać dziennik z podróży – może to być świetna pamiątka.",
  "89. Zabierz ze sobą grę planszową lub karty – urozmaicą one czas podczas złej pogody.",
  "90. Zaplanuj zakupy, tankowanie wody oraz opróżnienie toalety i szarej wody dzień wcześniej.",
  "91. Weź pod uwagę, że gotowanie w kamperze lub campervanie zajmuje znacznie więcej czasu niż w mieszkaniu.",
  "92. Przygotuj się na częste sprzątanie auta – zaopatrz się w zmiotkę lub odkurzacz.",
  "93. Przygotuj się na obecność licznych owadów – nie tylko komarów. Moskitiera może być jedynie częściowym rozwiązaniem.",
  "94. Nie zapalaj wieczorem światła przy uchylonych drzwiach.",
  "95. Przed wyjazdem sprawdź stan koła zapasowego oraz zaopatrz się w zestaw do naprawy opony – pozwoli Ci to dojechać do najbliższej wulkanizacji.",
  "96. Bądź gotowy wyjść ze swojej strefy komfortu.",
  "97. Jeśli pracujesz zdalnie, zadbaj o wygodne miejsce do pracy – leżak i plaża wyglądają dobrze tylko na zdjęciach.",
  "98. Każdy dzień to przygoda – traktuj ją jako dobrą zabawę.",
  "99. Jeśli podróżujesz ze zwierzakiem, trzymaj go blisko auta.",
  "100. Gdy w telefonie braknie zasięgu, warto mieć przy sobie papierową mapę.",
  "101. Warunki pogodowe podczas spaceru mogą się nagle zmienić. Warto mieć przy sobie płaszcz przeciwdeszczowy, który zmieścisz w kieszeni.",
  "102. Przed podróżą sprawdź ważność paszportu oraz innych dokumentów.",
  "103. Wyrób Europejską Kartę Ubezpieczenia Zdrowotnego (EKUZ).",
  "104. Zaopatrz się w mały czajnik do zagotowania wody na kawę – zaoszczędzisz czas i wodę.",
  "105. Pamiętaj o kremie z filtrem UV – latem, zimą, a nawet podczas wędrówek w góry.",
  "106. Rób listę zakupów – unikniesz w ten sposób niepotrzebnych lub dodatkowych wydatków.",
  "107. Nie pakuj się na ostatnią chwilę – przygotuj potrzebne rzeczy przynajmniej dwa dni wcześniej.",
  "108. Butelka alkoholu lub inny prezent to dobry pomysł, by podziękować za pomoc.",
  "109. Jeśli jesteś blisko stacji paliw i świeci się rezerwa, zatankuj – kolejna stacja może być za daleko.",
  "110. Dziel się swoimi doświadczeniami z innymi.",
  "111. Gdy nadarzy się okazja do zatankowania wody lub opróżnienia toalety, zrób to – podobnie jak przy tankowaniu paliwa, nigdy nie wiesz, kiedy pojawi się kolejna szansa.",
  "112. Jeśli podróżujesz z kimś, szczególnie w krajach spoza UE, warto ustalić sposób komunikacji w sytuacji braku internetu.",
  "113. Jeśli masz złe przeczucia odnośnie stanu swojego pojazdu, nie ignoruj ich.",
  "114. Przy naprawie samochodu zaczynaj od najdroższych elementów. Jeśli planujesz naprawy w tańszym kraju, pamiętaj, że może Cię to kosztować dwa razy więcej.",
  "115. Jeśli masz złe przeczucia co do miejsca, w którym zamierzasz nocować, poszukaj innego – nie kusić losu.",
  "116. Nie odkładaj śniadania na później – w ciągu dnia wiele się dzieje, a pierwszy posiłek, o 19:00, zwykle nazywany jest kolacją.",
  "117. Jeśli czas nie pokrywa się z przebytą liczbą kilometrów, rozważ zmianę miejscówki – może to oznaczać, że droga jest bardzo słabej jakości lub off-road.",
  "118. Jeśli Google Maps źle wskazuje drogę, warto sprawdzić ją w innej aplikacji.",
  "119. Jeśli coś się zepsuło, a następnie samo się naprawiło, to oznacza, że nadal jest uszkodzone.",
  "120. Teytytki, szara taśma i WD-40 – miej je zawsze pod ręką.",
  "121. Jeśli wczorajsza impreza się przedłużyła, odczekaj, zanim wsiądziesz za kierownicę, lub udaj się na komisariat policji i poproś o badanie alkomatem.",
  "122. Jeśli jesteś w górach i spadł śnieg, poczekaj, aż pojawi się pług śnieżny. Jedź za nim – to znacznie ułatwi drogę.",
  "123. Jeżeli gdzieś wyjeżdżasz, zawsze zabierz ze sobą paszport – nigdy nie wiesz, gdzie przygoda Cię poniesie.",
  "124. Zapoznaj się z zasadami ruchu drogowego oraz kulturą jazdy tamtejszych kierowców.",
  "125. Sprawdź, jakie jest obowiązkowe wyposażenie samochodu w kraju, do którego jedziesz, oraz przez które przejeżdżasz (np. kamizelki, gaśnica, trójkąt).",
  "126. Pamiętaj o zabraniu Zielonej Karty, gdy wyjeżdżasz autem za granicę.",
  "127. Jeśli to możliwe, wykup dodatkowe ubezpieczenie obowiązujące w kraju, do którego jedziesz.",
  "128. Jeśli planujesz wyjazd poza Unię Europejską, sprawdź wymagania obowiązujące w danym kraju.",
  "129. Sprawdź, czy w kraju, do którego jedziesz, wymagane są szczepienia.",
  "130. Zapytaj lokalnych mieszkańców o atrakcje w okolicy.",
  "131. Zapoznaj się z kulturą danego kraju, np. z lokalnymi gestami.",
  "132. Zawsze zapinaj pasy bezpieczeństwa – mogą uratować Ci życie.",
  "133. Unikaj prowadzenia pojazdu po spożyciu alkoholu, nawet po jednym piwie.",
  "134. Warto mieć w aucie dodatkowe źródło światła – np. lampkę LED na baterie lub powerbank. Może uratować sytuację podczas awarii po zmroku.",
  "135. Jeśli zatrzymujesz się na noc przy drodze, wybieraj miejsca dobrze oświetlone i monitorowane.",
  "136. Naucz się kilku podstawowych zwrotów w lokalnym języku – wystarczy „dziękuję”, „proszę” i „gdzie jest…?”.",
  "137. W upalne dni zakrywaj okna od strony słońca – to znacząco obniży temperaturę wewnątrz pojazdu.",
  "138. Zawsze miej pod ręką ładowarkę samochodową – telefon to nie tylko kontakt ze światem, ale też GPS, aparat i latarka.",
  "139. Jeśli jedziesz w nowe miejsce, sprawdź wcześniej opinie innych podróżników – nie wszystko, co wygląda pięknie na zdjęciu, jest bezpieczne.",
  "140. Pamiętaj o częstym wietrzeniu auta – zwłaszcza, jeśli masz ze sobą zwierzaka.",
  "141. Zapisuj codziennie swoje wydatki – nawet niewielkie kwoty potrafią się szybko zsumować.",
  "142. Jeśli nocujesz blisko morza, sprawdź prognozę pływów – w nocy woda może podejść znacznie bliżej.",
  "143. Zawsze miej przygotowany plan B na nocleg – czasem miejscówka może być zajęta lub nieprzyjazna.",
  "144. Trzymaj zestaw zapasowych bezpieczników – jeden z nich może zdecydować, czy lodówka działa, czy nie.",
  "145. W chłodne dni zasłaniaj szyby od wewnątrz – folia termiczna lub koc odbijający ciepło naprawdę działa.",
  "146. Jeśli podróżujesz dłużej, raz na jakiś czas zrób „dzień serwisowy” – przegląd techniczny, pranie, porządki.",
  "147. Gdy wchodzisz do miejsc kultu religijnego, zachowaj odpowiedni strój i szacunek – nawet jeśli to tylko szybkie zwiedzanie.",
  "148. Pamiętaj, że niektóre kraje mają inne normy dotyczące gniazdek elektrycznych – zaopatrz się w adapter.",
  "149. Trzymaj torbę z ubraniami na zmianę łatwo dostępną – nagła zmiana pogody potrafi zaskoczyć.",
  "150. Jeśli coś zgubisz lub zostawisz, wróć po to jak najszybciej – z każdą godziną szanse maleją.",
  "151. Naucz się podstawowych procedur w razie pożaru lub zalania auta – sekundy mają znaczenie.",
  "152. Jeśli masz kuchenkę gazową, kontroluj poziom gazu i zawsze zakręcaj butlę po gotowaniu.",
  "153. Nie śpiesz się. Czasami warto spędzić jeden dzień dłużej w miejscu, które daje spokój i dobrą energię.",
  "154. Jeśli planujesz zostać w jednym miejscu dłużej, ustaw auto tak, by poranne słońce świeciło Ci w stronę kuchni – gotowanie będzie przyjemniejsze.",
  "155. Przed wyjazdem przetestuj nowy sprzęt – nic tak nie frustruje jak grill, który nie działa na głodzie.",
  "156. Zapisuj fajne miejsca, nawet jeśli nie zostajesz – możesz wrócić tu innym razem albo polecić znajomym.",
  "157. Prowadź dziennik zużycia paliwa – pomoże Ci ocenić, czy auto pracuje poprawnie.",
  "158. Upewnij się, że masz fizyczną kopię ważnych dokumentów – w razie kradzieży lub awarii telefonu mogą się przydać.",
  "159. Nie parkuj zbyt blisko innych pojazdów – daj sobie i innym przestrzeń.",
  "160. Jeśli możesz, unikaj jazdy nocą – łatwiej o błędy i trudniej o pomoc w razie potrzeby.",
  "161. Przynajmniej raz w tygodniu dokładnie posprzątaj wnętrze – podróż to nie powód, by żyć w chaosie.",
  "162. Zostaw zapasowe kluczyki w innym miejscu niż oryginalne – np. przyczepione magnesem pod autem.",
  "163. Jeśli parkujesz w naturze, sprawdź, czy miejsce nie jest siedliskiem dzikich zwierząt – nie chcesz obudzić się obok dzika.",
  "164. Wysoka wilgotność? Używaj pochłaniaczy wilgoci lub otwieraj okna przy dobrej pogodzie.",
  "165. Nie zostawiaj jedzenia na zewnątrz – mrówki i osy potrafią zjawić się szybciej niż się spodziewasz.",
  "166. Załóż mały notes z kodami do bramek, campingów i innych istotnych informacji – nie wszystko jest online.",
  "167. Przed odjazdem zawsze zrób „obchód” auta – sprawdź, czy wszystko zamknięte, odłączone i zabezpieczone.",
  "168. Korzystaj z lokalnych targów i bazarków – nie tylko taniej, ale i smaczniej.",
  "169. Pamiętaj o osłonie przeciwsłonecznej na szybę – wnętrze auta nie będzie przypominać piekarnika.",
  "170. W miejscach, gdzie są owady, używaj naturalnych odstraszaczy – np. olejku z cytryny, lawendy czy eukaliptusa.",
  "171. Trzymaj narzędzia w jednym, łatwo dostępnym miejscu – skrzynka na narzędzia to Twój przyjaciel.",
  "172. Zanim rozstawisz się na noc, sprawdź poziom – czasem drobna górka potrafi zamienić sen w walkę o równowagę.",
  "173. Nie zostawiaj urządzeń elektronicznych w pełnym słońcu – łatwo się przegrzewają.",
  "174. Zrób zdjęcia dokumentów, tablicy rejestracyjnej i numeru VIN – mogą się przydać za granicą.",
  "175. Pamiętaj o ładowaniu powerbanków – w razie braku prądu możesz nadal działać.",
  "176. Zostaw karteczkę z kontaktem w widocznym miejscu – ktoś może próbować się z Tobą skontaktować w razie problemu.",
  "177. W upalne dni gotuj rano lub wieczorem – w południe lepiej odpoczywać.",
  "178. W podróży trzymaj się rutyny – poranne rozciąganie, kawa, 15 minut porządków – małe rytuały dają spokój.",
  "179. Naucz się podstawowych komend dla swojego zwierzaka – bezpieczeństwo przede wszystkim.",
  "180. Staraj się spać z głową wyżej – nawet niewielki kąt nachylenia pomaga w oddychaniu.",
  "181. Jeśli coś działa dziś, nie znaczy, że zadziała jutro – bądź przygotowany na awarie.",
  "182. Zawsze sprawdzaj stan hamulców przed długą trasą w górach – lepiej zawczasu, niż w dolinie.",
  "183. Otwieraj się na rozmowy z lokalnymi – to najlepszy przewodnik, jakiego znajdziesz.",
  "184. Pamiętaj, że im mniej rzeczy masz, tym łatwiej się żyje – minimalizm to sprzymierzeniec podróży.",
  "185. Zawsze miej zapasowe baterie lub ładowarkę słoneczną – energia to klucz do niezależności.",
  "186. Jeśli planujesz biwak z dala od cywilizacji, zostaw komuś informację o swojej lokalizacji.",
  "187. Zadbaj o odpowiednie oznakowanie kampera w nocy – odblaski mogą uratować życie.",
  "188. Staraj się tankować w tańszych regionach – ceny paliwa mogą się bardzo różnić.",
  "189. W miejscach publicznych staraj się nie rzucać w oczy – podróżnik, który nie przyciąga uwagi, jest bezpieczniejszy.",
  "190. Często dezynfekuj ręce – szczególnie po tankowaniu, korzystaniu z toalet publicznych i zakupach.",
  "191. Jeśli nocujesz w miejscu z zasięgiem Wi-Fi, skorzystaj z okazji do aktualizacji aplikacji i pobrania offline'owych materiałów.",
  "192. Zrób zdjęcie miejsca, w którym zostawiasz auto – szczególnie w większych miastach.",
  "193. W razie awarii staraj się zachować spokój – każda sytuacja ma rozwiązanie.",
  "194. Sprawdź, jakie są lokalne święta i dni wolne – może to wpłynąć na dostępność usług.",
  "195. Unikaj jazdy na oparach – zawsze miej w baku rezerwę bezpieczeństwa.",
  "196. Zadbaj o odpowiednią wentylację podczas gotowania – opary w małej przestrzeni mogą być szkodliwe.",
  "197. Zabieraj ze sobą tylko sprawdzone aplikacje – mniej znaczy więcej, jeśli chodzi o stabilność.",
  "198. Jeśli coś wymaga naprawy, napraw to od razu – odwlekanie pogarsza sytuację.",
  "199. Wybierając miejsce na nocleg, zwracaj uwagę na nachylenie terenu – może zepsuć sen.",
  "200. Rozważ zamontowanie czujników gazu i dymu – bezpieczeństwo to podstawa.",
  "201. Przed wyjazdem z miejsca postoju zrób szybką checklistę – unikniesz zapomnienia ważnych rzeczy.",
  "202. Sprawdź pogodę nie tylko na dany dzień, ale i na kolejne dni w danym regionie.",
  "203. Jeśli często zmieniasz kraj, rozważ zakup międzynarodowej karty SIM lub eSIM.",
  "204. Jeśli parkujesz w miejscu publicznym, nie zostawiaj niczego na widoku.",
  "205. Dostosuj nawyki żywieniowe do lokalnej dostępności produktów – ułatwi to zakupy.",
  "206. Jeśli jesteś zmęczony, zrób postój – zmęczenie za kierownicą bywa groźniejsze niż alkohol.",
  "207. Warto mieć składany stolik i krzesło – dają komfort niezależnie od warunków.",
  "208. Zadbaj o porządek w kablach i ładowarkach – to drobne, ale potrafią irytować.",
  "209. Notuj miejsca, gdzie udało Ci się przenocować – mogą się przydać w przyszłości.",
  "210. Jeśli masz rower lub hulajnogę – zabezpiecz go porządnym zapięciem.",
  "211. Znajdź swój rytm podróżowania – nie kopiuj stylu innych, bo każda podróż jest inna.",
  "212. Nie oceniaj miejsca po pierwszym wrażeniu – czasem warto poczekać do rana.",
  "213. Jeśli planujesz dłuższy postój – sprawdź, czy jest dostęp do wody, toalety i śmietników.",
  "214. Dziel się miejscówkami tylko z zaufanymi osobami – nie każde miejsce znosi dużą popularność.",
  "215. Pamiętaj, że czasem mniej znaczy więcej – nie odwiedzaj wszystkiego na siłę.",
  "216. Jeśli masz trudność z zasypianiem – spróbuj białego szumu lub aplikacji relaksacyjnych.",
  "217. Zapisuj swoje trasy – mogą stać się inspiracją dla innych (lub dla Ciebie za rok).",
  "218. Pamiętaj, że nie każda awaria to koniec świata – potraktuj ją jak część przygody.",
  "219. Zawsze miej coś do jedzenia „na czarną godzinę” – najlepiej długo przydatnego do spożycia.",
  "220. Jeśli korzystasz z aplikacji do parkowania, zostaw opinię – pomożesz innym.",
  "221. Często zmieniaj wodę w zbiornikach – unikniesz nieprzyjemnego zapachu.",
  "222. Naucz się kilku ćwiczeń rozciągających – ciało w podróży potrzebuje ruchu.",
  "223. Używaj woreczków próżniowych do przechowywania ubrań – zaoszczędzisz miejsce.",
  "224. Jeśli coś się nie zmieściło – to znaczy, że nie było potrzebne.",
  "225. Nie zapominaj o własnym zdrowiu psychicznym – pozwól sobie na leniwe dni.",
  "226. Zadbaj o światło do czytania – wieczory w kamperze są idealne do książek.",
  "227. Nie zostawiaj kluczyków w stacyjce – nawet na chwilę.",
  "228. Zawsze sprawdzaj, czy masz zapięte wszystkie zamki przed ruszeniem.",
  "229. Stosuj zasadę: co się nie użyło przez 30 dni – można zostawić lub oddać.",
  "230. Jeśli jedziesz w nowe miejsce – sprawdź, czy są tam bankomaty i sklepy.",
  "231. Zapisuj imiona ludzi, których poznajesz – to buduje relacje.",
  "232. Nie odkładaj zdjęć „na później” – rób kopie zapasowe regularnie.",
  "233. Zawsze miej notatnik – nawet mały – do szybkich zapisów i obserwacji.",
  "234. Przypnij zapasowy kluczyk gdzieś w ukryciu – kiedyś może uratować Ci skórę.",
  "235. Jeśli ktoś pomógł Ci bezinteresownie – zapisz to i odwdzięcz się komuś innemu.",
  "236. Testuj sprzęty w ekstremalnych warunkach zanim wyjedziesz – np. niskie temperatury.",
  "237. Dobrze mieć taśmę dwustronną, rzepy i opaski – drobiazgi, które ratują porządek.",
  "238. Miej w telefonie skan prawa jazdy i dowodu – na wszelki wypadek.",
  "239. Jeśli coś rozlałeś – wyczyść to od razu. Później będzie trudniej.",
  "240. Rób czasem „dzień offline” – bez GPS, bez internetu, tylko Ty i droga.",
  "241. Nie bądź niewolnikiem planu – zmiana trasy to nie porażka.",
  "242. Jeśli masz pasję – zabierz ją w drogę. Rysowanie, gra, muzyka – cokolwiek.",
  "243. Zamiast kupować pamiątki, zbieraj kamyki, muszle lub rysuj miejsca, które odwiedzasz.",
  "244. Daj sobie prawo do odpoczynku – nie musisz „zaliczać” wszystkiego.",
  "245. Pamiętaj, że podróżowanie to też odpowiedzialność – jesteś gościem.",
  "246. Nie używaj zbyt jaskrawych świateł nocą – szanuj sąsiadów na postoju.",
  "247. Miej zawsze przy sobie coś słodkiego – może poprawić nastrój w trudnych chwilach.",
  "248. Jeśli boisz się gdzieś spać – nie śpij tam. Zawsze słuchaj intuicji.",
  "249. Nie porównuj swojej podróży do cudzej – każda droga jest inna i wartościowa.",
  "250. Nie zapomnij się uśmiechać – nawet w najgorszy dzień.",
  "251. Jeśli zostajesz na noc przy plaży, upewnij się, że nie jesteś w strefie przypływu.",
    "252. Nie rozstawiaj się zbyt blisko atrakcji turystycznych – rano mogą pojawić się tłumy.",
    "253. Staraj się nie zostawiać kampera na długo bez opieki w nieznanych miejscach.",
    "254. Jeżeli masz małą przestrzeń – sprzątaj codziennie. Bałagan rośnie błyskawicznie.",
    "255. Gotując na zewnątrz, zawsze miej pod ręką wodę do gaszenia ognia.",
    "256. Szukaj równowagi między eksploracją a odpoczynkiem.",
    "257. Współdziel przestrzeń z szacunkiem – nie wszyscy chcą rozmawiać.",
    "258. Zawsze parkuj tak, byś mógł łatwo wyjechać.",
    "259. Zanim otworzysz markizę lub stół – upewnij się, że nie blokujesz przejścia.",
    "260. Jeśli nie jesteś pewien nawierzchni – sprawdź ją pieszo.",
    "261. Nie hałasuj wieczorem – inni mogą już odpoczywać.",
    "262. Zabierz ze sobą zapas kawy lub herbaty – poranki są ważne.",
    "263. Miej w aucie miejsce, które będzie „twoją strefą spokoju”.",
    "264. Gdy pada – nie narzekaj, tylko się dostosuj.",
    "265. Naucz się prostych napraw – od podklejenia okna po wymianę bezpiecznika.",
    "266. Nie zostawiaj sprzętu turystycznego bez opieki w tłocznych miejscach.",
    "267. Jeśli masz możliwość – bądź pomocny dla innych vanliferów.",
    "268. Zbieraj inspiracje – zapisuj, co zadziałało u innych.",
    "269. Czasem warto zapłacić za nocleg – dla bezpieczeństwa lub komfortu.",
    "270. Nie lekceważ komunikatów pogodowych – mogą uratować dzień (lub noc).",
    "271. Korzystaj z bibliotek lub kafejek – to dobre miejsca na Wi-Fi i odpoczynek.",
    "272. Trzymaj w bagażniku zestaw ubrań „na każdą pogodę”.",
    "273. Warto mieć przy sobie trochę gotówki w lokalnej walucie – nie wszędzie działa karta.",
    "274. Jeśli robisz zakupy – wspieraj lokalne biznesy.",
    "275. Nawet jednodniowy postój zasługuje na dobrą organizację.",
    "276. Ustal z partnerem „czas offline” – dla siebie nawzajem.",
    "277. Wycisz telefon przynajmniej raz dziennie – dla zdrowia psychicznego.",
    "278. Jeśli możesz – zadbaj o zieleń wokół siebie: podlej drzewko, posprzątaj, posadź coś.",
    "279. Pamiętaj, że mniej znaczy więcej – nie przeładowuj auta.",
    "280. Gdy nie możesz spać – wyjdź na krótki spacer, to pomaga.",
    "281. Sprawdź lokalne zasady parkowania – mogą się różnić nawet między miastami.",
    "282. Zrób czasem dzień bez jazdy – regeneracja jest równie ważna.",
    "283. Jeśli ktoś zaprosi Cię na obiad – weź coś w zamian.",
    "284. Korzystaj z aplikacji pogodowych, ale miej własne oczy – chmury mówią wiele.",
    "285. Jeśli widzisz, że komuś trudniej – zapytaj, czy nie potrzebuje pomocy.",
    "286. Przed dłuższą trasą zawsze sprawdź ciśnienie w oponach.",
    "287. Gdy masz zły dzień – przypomnij sobie, dlaczego ruszyłeś w tę drogę.",
    "288. Zachowuj lokalne przysmaki w notatniku – smak też jest wspomnieniem.",
    "289. Przetrzyj panele solarne – brudna powierzchnia to mniej energii.",
    "290. Przechowuj worki na śmieci w kilku miejscach – zawsze się przydadzą.",
    "291. Jeśli jedziesz z dziećmi – wprowadź rytuały i zasady, które dają im poczucie bezpieczeństwa.",
    "292. Po każdym tankowaniu paliwa – sprawdź również stan płynów.",
    "293. Nie zostawiaj papieru toaletowego w naturze – nawet tego biodegradowalnego.",
    "294. Znajdź czas na rozmowy z lokalnymi – to najlepsze źródło wiedzy o okolicy.",
    "295. Nie bądź nachalny – nie każdy chce być częścią społeczności vanlife.",
    "296. Zrób listę rzeczy, których nie zabierzesz następnym razem – ucz się z doświadczenia.",
    "297. Pamiętaj, że mniej planów = więcej przygód.",
    "298. Czasem niech wszystko działa… ale nic nie rób.",
    "299. Śledź fazy księżyca – noc pod pełnią może być magiczna.",
    "300. Nie zapomnij – najlepsze wspomnienia tworzą się w najprostszych chwilach.",
  "301. Zainstaluj maty antypoślizgowe przy wejściu do kampera, by uniknąć potknięć.",
    "302. Utwórz cyfrową i papierową kopię ważnych dokumentów (dowód, paszport) i przechowuj je w oddzielnych miejscach.",
    "303. Przechowuj apteczkę w dwóch miejscach – w kabinie i w miejscu dostępnym z zewnątrz.",
    "304. Oznacz kable i przewody kolorowymi taśmami, by szybko odnaleźć je w razie awarii.",
    "305. Zainstaluj w drzwiach czujnik oparów gazu.",
    "306. Umieść magnes z zapasowym kompletem kluczy pod pojazdem w odpornej na warunki metalowej skrzynce.",
    "307. Sprawdź odporność złącz wodnych na niskie temperatury, by uniknąć pęknięć zimą.",
    "308. Zainwestuj w przenośny syntezator dźwięku (white noise) na hałaśliwe noce.",
    "309. Zaznacz na mapie aplikacji GPS źródła awaryjnej pomocy medycznej.",
    "310. Korzystaj z aplikacji do monitorowania pogody satelitarnej.",
    "311. Przechowuj w lodówce kamperowej woreczek z lodem w kremowej ściance, by dłużej utrzymać niską temperaturę.",
    "312. Noś w portfelu mini kompas awaryjny.",
    "313. Regularnie czyść filtry powietrza i wentylatory, aby uniknąć zapychania się instalacji.",
    "314. Zrób zdjęcia wnętrza kampera przed wyjazdem, by mieć dowód stanu w razie szkody.",
    "315. Sprawdź poziom szarej i czarnej wody zawsze przed dłuższą trasą.",
    "316. Dołącz instrukcję obsługi do każdego urządzenia w formacie kodu QR.",
    "317. Przechowuj dodatkowy zestaw narzędzi w miejscu dostępnym z zewnątrz pojazdu.",
    "318. Testuj działanie klimatyzacji i ogrzewania podczas postoju przed wyjazdem.",
    "319. Trzymaj taśmę termiczną i kablową do szybkich napraw.",
    "320. Zaopatrz się w zapasowe żarówki do oświetlenia kampera.",
    "321. Zainstaluj moduł Bluetooth do zdalnej kontroli oświetlenia i ogrzewania.",
    "322. Przypnij materiały odblaskowe na zewnętrznych punktach auta.",
    "323. Zapisuj poziom paliwa i przebiegi tras w dedykowanej aplikacji.",
    "324. Używaj worków próżniowych do ubrań, aby zaoszczędzić miejsce.",
    "325. Zainwestuj w przenośne urządzenie do pomiaru jakości powietrza.",
    "326. Zaopatrz się w przenośny ekspres do kawy na kapsułki.",
    "327. Zabezpiecz telefon w wodoodpornym etui na wypadek deszczu.",
    "328. Korzystaj z drewnianych akcesoriów kuchennych, by ograniczyć plastikowe odpady.",
    "329. Zamontuj filtr wody carbon block przy kranie kampera.",
    "330. Ustal procedurę alarmową na wypadek wycieku gazu.",
    "331. Regularnie sprawdzaj szczelność uszczelek w drzwiach i oknach.",
    "332. Przygotuj awaryjną latarkę z możliwością ładowania korbką.",
    "333. Noś ze sobą mini powerbank solarny.",
    "334. Zapisuj rozmowy telefoniczne z pomocą drogową dla dowodu i bezpieczeństwa.",
    "335. Zainstaluj aplikację do identyfikacji roślin i zwierząt w terenie.",
    "336. Korzystaj ze wkładek termicznych w oknach na czas chłodniejszych nocy.",
    "337. Zainwestuj w przedłużacz sieciowy z ochroną przeciwprzepięciową.",
    "338. Noś przy sobie mini apteczkę na oparzenia i drobne skaleczenia.",
    "339. Przechowuj worki biodegradowalne na odpady organiczne.",
    "340. Zainstaluj filtr HEPA do oczyszczania powietrza wewnątrz pojazdu.",
    "341. Testuj moduł ogrzewania na gaz w ujemnych temperaturach.",
    "342. Stwórz harmonogram przeglądów i zapisz terminy w kalendarzu.",
    "343. Używaj drewnianych łyżek i szpatułek podczas gotowania na ognisku.",
    "344. Zabezpiecz kable USB w twardym etui, by uniknąć uszkodzeń.",
    "345. Zapisz przypomnienie o przeglądzie technicznym swojego pojazdu",
    "346. Zaopatrz się w mini zestaw do naprawy elektroniki (lutownica, taśmy, kabelki).",
    "347. Zapisuj dziennik serwisowy w aplikacji mobilnej lub notatniku.",
    "348. Uporządkuj przewody i węże tak, by nie plątały się podczas jazdy.",
    "349. Noś maskę przeciwpyłową na drogi nieutwardzone, by chronić drogi oddechowe.",
    "350. Ciesz się każdą chwilą podróży, ale zawsze zachowuj rozsądek i priorytet dla bezpieczeństwa.",
  ]

